# Chimeric receptors simulations - Assertion testing

In [1]:
%load_ext autoreload
%autoreload 2

import sys
import os
        
import maboss
from maboss import temporal_logic as tl

### Sanity test (apoptosis and prolif cannot happen at the same time)

In [2]:
bnd = "model_Tcell.bnd"
cfg = "model_Tcell.cfg"

nodes = list(maboss.load(bnd,cfg).network.keys())
#print(nodes)

ON = [0,1]
OFF = [1,0]
RANDOM = [0.5, 0.5]

all_nodes_random_init = [{'node':node,'istate':RANDOM} for node in nodes]
#print(all_nodes_off)

# initial conditions
i_c_TME = [
    {'node':'LCK','istate':ON},
    {'node':'CD45','istate':ON},
    {'node':'CD8','istate':ON},
    {'node':'TIM3_L','istate':ON},
    {'node':'IFNG_L','istate':ON},
    {'node':'IL2_L','istate':ON},
    {'node':'IL4_L','istate':ON},
    {'node':'TGFB_L','istate':ON},
    {'node':'L41BB','istate':ON},
    {'node':'FAS_L','istate':ON},
    {'node':'TIGIT_L','istate':ON},
    {'node':'PD1_L','istate':ON},
    {'node':'IL7_L','istate':ON},
    {'node':'CD80_86','istate':ON},
    {'node':'IL12_L','istate':ON},
    {'node':'IL27_L','istate':ON},
    {'node':'ICOS_L','istate':ON},
]

i_c_MM = [
    {'node':'LCK','istate':ON},
    {'node':'CD45','istate':ON},
    {'node':'CD8','istate':ON},
    {'node':'TIM3_L','istate':ON},
    {'node':'IFNG_L','istate':ON},
    {'node':'IL2_L','istate':ON},
    {'node':'IL4_L','istate':ON},
    {'node':'TGFB_L','istate':ON},
    {'node':'L41BB','istate':ON},
    {'node':'FAS_L','istate':ON},
    {'node':'TIGIT_L','istate':ON},
    {'node':'PD1_L','istate':ON}
]

i_c_antigen = [
    {'node':'LCK','istate':ON},
    {'node':'CD45','istate':ON},
    {'node':'CD8','istate':ON}
]

# CD4
# initial states to have types of cells
CD4 = all_nodes_random_init + [{'node':'iden_CD4','istate':ON}]
CD4_endo = CD4 + [{'node': 'iden_abTCR', 'istate':ON}]
CD4_is_CART =  CD4 + i_c_TME + [{'node':'iden_CAR','istate':ON}]
CD4_is_Tcell = [{'node':'iden_abTCR','istate':ON}] + CD4
CD4_is_TEG001 = [{'node':'iden_gdTCR','istate':ON},] + CD4
CD4_is_TEG103_trunc = [{'node':'iden_TR103','istate':ON},{'node':'iden_gdTCR','istate':ON}] + CD4
CD4_is_NKG2D_CD28 = [{'node':'iden_NKCD28','istate':ON}, {'node':'iden_gdTCR','istate':ON}] + CD4
CD4_is_NKG2D_41BB = [{'node':'iden_NK41BB','istate':ON}, {'node':'iden_gdTCR','istate':ON}] + CD4

#CD8
CD8 = all_nodes_random_init + [{'node':'iden_CD8','istate':ON}]
CD8_endo = CD8 + [{'node': 'iden_abTCR', 'istate':ON}]

th1_phenotype_ic = [
    {'node': 'IL12_L', 'istate': OFF},
    {'node': 'IFNG_L', 'istate': ON},
    {'node': 'IL4_L', 'istate': ON}
]

th2_phenotype_ic = [
    {'node': 'IL12_L', 'istate': OFF},
    {'node': 'IFNG_L', 'istate': OFF},
    {'node': 'IL4_L', 'istate': ON}
]

th1_phenotype_mut = "IL12_L:OFF IFNG_L:ON IL4_L:ON"
th2_phenotype_mut = "IL12_L:OFF IFNG_L:OFF IL4_L:ON"

### Run the simulations and the querying
if you want to use 2 initial conditions use `list1.extend(list2)`
**eg: CART with TME : `tl.MaBoSSEvaluator.querying(assertions,cfg,bnd,is_CART.extend(i_c_TME)`**

- assertion 2: th1 is a node, look for output th1, mutation IL-12 ->1 IL-4 -> 0
- assertion 3: same for th2
- assertion 4: same assertion 1 but different outputs
- assertion 5: EOMES node

In [3]:
CD4_endo_list_phenotypes = [
    f"Inc(node:Th1) / [ ] [ {th1_phenotype_mut} ] [ ]", #CD4 T cells acquire a Th1 phenotype under IFNG_L, IL12_L, and under no IL4_L.
    f"Inc(node:Th2) / [ ] [ {th2_phenotype_mut} ] [ ]", #CD4 T cells acquire a Th2 phenotype under IL4_L and no IFNG_L nor IL12_L
]

CD4_endo_list_random_ic = [
    f"Inc(node:GZMB,PRF1,IFNg,TBET,RUNX3,ThPOK,EOMES) / [ ] [ {th1_phenotype_mut} ] [ ]", #CD4 T cells under IFNG_L, IL12_L, and under no IL4_L, increase of GZMB, PRF1, IFNg, TBET, RUNX3, ThPOK and EOMES
    f"Inc(node:GZMB,PRF1,IFNg,TBET,RUNX3,ThPOK,EOMES) / [ ] [ {th1_phenotype_mut} ] [ comb ]"
    f"Inc(node:EOMES) / [ ] [ {th2_phenotype_mut} ] [ ]", #CD4 T cells under IL4_L and no IFNG_L nor IL12_L increase EOMES
    f"Dec(node:PRF1,GZMB,GNLY,IFNg) / [ ] [ RUNX3:OFF ] [ ]", #RUNX3 KO results in PRF1, GZMB and GNLY decrease and has no effect in IFNg.
    f"Dec(node:PRF1,GZMB,GNLY,IFNg) / [ ] [ RUNX3:OFF ] [ comb ]"
    f"Dec(node:PRF1,GZMB,TNFa,GZMK,IFNg,GNLY) / [ ] [ TBET:OFF ] [ ]", # TBET KO results in decrease of PRF1, GZMB (but not as much as RUNX3 KO), TNFa, GZMK, IFNg and GNLY.
    f"Dec(node:PRF1,GZMB,TNFa,GZMK,IFNg,GNLY) / [ ] [ TBET:OFF ] [ comb ]",
    f"Inc(node:PRF1,GZMB) / [ ] [ EOMES:OFF ] [ ]", #EOMES KO has no effect on PRF1 or GZMB
    f"Inc(node:PRF1,GZMB) / [ ] [ ThPOK:OFF ] [ ]", #ThPOK KO increased PRF1 and GZMB
    f"Inc(node:PRF1,GZMB) / [ ] [ EOMES:OFF ] [ comb ]", #EOMES KO has no effect on PRF1 or GZMB with comb
    f"Inc(node:PRF1,GZMB) / [ ] [ ThPOK:OFF ] [ comb ]", #ThPOK KO increased PRF1 and GZMB with comb
    #int41BB KI AND CD3 KI decrease Apoptosis to a lower level than CD3 KI or int41BB KI
    f"Dec(node:Apoptosis) / [ ] [ int41BB:ON CD3:ON ] [ ]",
    f"Dec(node:Apoptosis) / [ ] [ int41BB:ON CD3:OFF ] [ ]",
    f"Dec(node:Apoptosis) / [ ] [ int41BB:OFF CD3:ON ] [ ]",
    #int41BB KI AND CD3 KI increase proliferation, IFNg, GZMB, GZMK, PRF1, CD3 KI or int41BB KI have no effect.
    f"Inc(node:proliferation,IFNg,GZMB,GZMK,PRF1) / [ ] [ int41BB:ON CD3:ON ] [ ]",
    f"Inc(node:proliferation,IFNg,GZMB,GZMK,PRF1) / [ ] [ int41BB:ON CD3:OFF ] [ ]", #should show stable
    f"Inc(node:proliferation,IFNg,GZMB,GZMK,PRF1) / [ ] [ int41BB:OFF CD3:ON ] [ ]", #should show stable
    #int41BB KI AND CD3 KI increase proliferation, IFNg, GZMB, GZMK, PRF1, CD3 KI or int41BB KI have no effect. with comb
    f"Inc(node:proliferation,IFNg,GZMB,GZMK,PRF1) / [ ] [ int41BB:ON CD3:ON ] [ comb ]",
    f"Inc(node:proliferation,IFNg,GZMB,GZMK,PRF1) / [ ] [ int41BB:ON CD3:OFF ] [ comb ]", #should show stable
    f"Inc(node:proliferation,IFNg,GZMB,GZMK,PRF1) / [ ] [ int41BB:OFF CD3:ON ] [ comb ]", #should show stable
    #int41BB KI AND CD3 KI increase IL2 higher than int41BB KI
    f"Inc(node:IL2) / [ ] [ int41BB:ON CD3:ON ] [ ]",
    f"Inc(node:IL2) / [ ] [ int41BB:ON CD3:OFF ] [ ]",
    # and int41BB KI does so higher than CD3 KI
    f"Inc(node:IL2) / [ ] [ CD3:ON int41BB:OFF ] [ ]",
    # IL7_L decreases apoptosis
    f"Dec(node:Apoptosis) / [ ] [ IL7_L:ON ] [ ]",
    #IL2_L or IFNG_L increase TBET, BLIMP1, EOMES, GZMB and PRF1
    f"Inc(node:TBET,BLIMP1,EOMES,GZMB,PRF1) / [ ] [ IL2_L:ON IFNG_L:OFF ] [ ]",
    f"Inc(node:TBET,BLIMP1,EOMES,GZMB,PRF1) / [ ] [ IFNG_L:ON IL2_L:OFF ] [ ]",
    f"Inc(node:TBET,BLIMP1,EOMES,GZMB,PRF1) / [ ] [ IFNG_L:ON IL2_L:ON ] [ ]",
    #IL2_L or IFNG_L increase TBET, BLIMP1, EOMES, GZMB and PRF1 with comb
    f"Inc(node:TBET,BLIMP1,EOMES,GZMB,PRF1) / [ ] [ IL2_L:ON IFNG_L:OFF ] [ comb ]",
    f"Inc(node:TBET,BLIMP1,EOMES,GZMB,PRF1) / [ ] [ IFNG_L:ON IL2_L:OFF ] [ comb ]",
    f"Inc(node:TBET,BLIMP1,EOMES,GZMB,PRF1) / [ ] [ IFNG_L:ON IL2_L:ON ] [ comb ]",
    #TGFB_L and IL2_L increase Treg, FOXP3, IL2RA and IL10
    f"Inc(node:Treg,FOXP3,IL2RA,IL10) / [ ] [ IL2_L:ON TGFB_L:ON ] [ ]",
    #TGFB_L and IL2_L increase Treg, FOXP3, IL2RA and IL10 with comb
    f"Inc(node:Treg,FOXP3,IL2RA,IL10) / [ ] [ IL2_L:ON TGFB_L:ON ] [ comb ]",
]
output_CD4_endo_list_random_ic = ["GZMB","PRF1","IFNg","TBET","RUNX3","ThPOK","EOMES","GNLY","TNFa","GZMK","Apoptosis","proliferation","IL2","BLIMP1","Treg","FOXP3","IL2RA","IL10"]

CD4_endo_list_th1_ic = [
    f"Inc(node:GZMB,PRF1,IFNg,TBET,RUNX3,ThPOK,EOMES) / [ ] [ IFNG_L:ON IL12_L:ON IL4_L:OFF ] [ ]",#CD4 T cells under IFNG_L, IL12_L, and under no IL4_L, increase of GZMB, PRF1, IFNg, TBET, RUNX3, ThPOK and EOMES
    f"Inc(node:GZMB,PRF1,IFNg,TBET,RUNX3,ThPOK,EOMES) / [ ] [ IFNG_L:ON IL12_L:ON IL4_L:OFF ] [ comb ]",#CD4 T cells under IFNG_L, IL12_L, and under no IL4_L, increase of GZMB, PRF1, IFNg, TBET, RUNX3, ThPOK and EOMES with comb
    f"Dec(node:PRF1,GZMB,GNLY,IFNg) / [ ] [ RUNX3:OFF ] [ ]", #RUNX3 KO results in PRF1, GZMB and GNLY decrease and has no effect in IFNg.
    f"Dec(node:PRF1,GZMB,GNLY,IFNg) / [ ] [ RUNX3:OFF ] [ comb ]", #RUNX3 KO results in PRF1, GZMB and GNLY decrease and has no effect in IFNg with comb
    f"Dec(node:PRF1,GZMB,TNFa,GZMK,IFNg,GNLY) / [ ] [ TBET:OFF ] [ ]", # TBET KO results in decrease of PRF1, GZMB (but not as much as RUNX3 KO), TNFa, GZMK, IFNg and GNLY.
    f"Dec(node:PRF1,GZMB,TNFa,GZMK,IFNg,GNLY) / [ ] [ TBET:OFF ] [ comb ]", # TBET KO results in decrease of PRF1, GZMB (but not as much as RUNX3 KO), TNFa, GZMK, IFNg and GNLY.
    f"Inc(node:PRF1,GZMB) / [ ] [ EOMES:OFF ] [ ]", #EOMES KO has no effect on PRF1 or GZMB
    f"Inc(node:PRF1,GZMB) / [ ] [ ThPOK:OFF ] [ ]", #ThPOK KO increased PRF1 and GZMB
    f"Inc(node:PRF1,GZMB) / [ ] [ EOMES:OFF ] [ comb ]", #EOMES KO has no effect on PRF1 or GZMB with comb
    f"Inc(node:PRF1,GZMB) / [ ] [ ThPOK:OFF ] [ comb ]", #ThPOK KO increased PRF1 and GZMB with comb
]
output_CD4_endo_list_th1 = ["GZMB","PRF1","IFNg","TBET","RUNX3","ThPOK","EOMES","GNLY","TNFa","GZMK"]

CD4_endo_list_th2_ic = [
    f"Inc(node:EOMES) / [ ] [ IL4_L:ON IFNG_L:ON IL12_L:ON ] [ ]", #CD4 T cells under IL4_L and no IFNG_L nor IL12_L increase EOMES
]

CD4_endo_list_abTCR_L41BB = [
    #int41BB KI AND CD3 KI decrease Apoptosis to a lower level than CD3 KI or int41BB KI
    f"Dec(node:Apoptosis) / [ ] [ int41BB:ON CD3:ON ] [ ]",
    f"Dec(node:Apoptosis) / [ ] [ int41BB:ON CD3:OFF ] [ ]",
    f"Dec(node:Apoptosis) / [ ] [ int41BB:OFF CD3:ON ] [ ]",
    #int41BB KI AND CD3 KI increase proliferation, IFNg, GZMB, GZMK, PRF1, CD3 KI or int41BB KI have no effect.
    f"Inc(node:proliferation,IFNg,GZMB,GZMK,PRF1) / [ ] [ int41BB:ON CD3:ON ] [ ]",
    f"Inc(node:proliferation,IFNg,GZMB,GZMK,PRF1) / [ ] [ int41BB:ON CD3:OFF ] [ ]", #should show stable
    f"Inc(node:proliferation,IFNg,GZMB,GZMK,PRF1) / [ ] [ int41BB:OFF CD3:ON ] [ ]", #should show stable
    #int41BB KI AND CD3 KI increase proliferation, IFNg, GZMB, GZMK, PRF1, CD3 KI or int41BB KI have no effect. with comb
    f"Inc(node:proliferation,IFNg,GZMB,GZMK,PRF1) / [ ] [ int41BB:ON CD3:ON ] [ comb ]",
    f"Inc(node:proliferation,IFNg,GZMB,GZMK,PRF1) / [ ] [ int41BB:ON CD3:OFF ] [ comb ]", #should show stable
    f"Inc(node:proliferation,IFNg,GZMB,GZMK,PRF1) / [ ] [ int41BB:OFF CD3:ON ] [ comb ]", #should show stable
    #int41BB KI AND CD3 KI increase IL2 higher than int41BB KI
    f"Inc(node:IL2) / [ ] [ int41BB:ON CD3:ON ] [ ]",
    f"Inc(node:IL2) / [ ] [ int41BB:ON CD3:OFF ] [ ]",
    # and int41BB KI does so higher than CD3 KI
    f"Inc(node:IL2) / [ ] [ CD3:ON int41BB:OFF ] [ ]",
]
output_CD4_endo_list_abTCR_L41BB = ["Apoptosis","proliferation","IL2","IFNg","GZMB","GZMK","PRF1"]

CD4_endo_CAR41BB_i_c = [
    #THEMIS KO or SHP1 KO increase Apoptosis
    f"Inc(node:Apoptosis) / [ ] [ THEMIS:ON SHP1:ON ] [ ]",
    f"Inc(node:Apoptosis) / [ ] [ THEMIS:OFF SHP1:ON ] [ ]",
    f"Inc(node:Apoptosis) / [ ] [ THEMIS:ON SHP1:OFF ] [ ]",
]

CD8_list_random_ic = [
    #int41BB KI AND CD3 KI decrease Apoptosis to a lower level than CD3 KI or int41BB KI
    f"Dec(node:Apoptosis) / [ ] [ int41BB:ON CD3:ON ] [ ]",
    f"Dec(node:Apoptosis) / [ ] [ int41BB:ON CD3:OFF ] [ ]",
    f"Dec(node:Apoptosis) / [ ] [ int41BB:OFF CD3:ON ] [ ]",
    #int41BB KI AND CD3 KI increase proliferation, IFNg, GZMB, GZMK, PRF1, CD3 KI or int41BB KI have no effect.
    f"Inc(node:proliferation,IFNg,GZMB,GZMK,PRF1) / [ ] [ int41BB:ON CD3:ON ] [ ]",
    f"Inc(node:proliferation,IFNg,GZMB,GZMK,PRF1) / [ ] [ int41BB:ON CD3:OFF ] [ ]", #should show stable
    f"Inc(node:proliferation,IFNg,GZMB,GZMK,PRF1) / [ ] [ int41BB:OFF CD3:ON ] [ ]", #should show stable
    #int41BB KI AND CD3 KI increase proliferation, IFNg, GZMB, GZMK, PRF1, CD3 KI or int41BB KI have no effect. with comb
    f"Inc(node:proliferation,IFNg,GZMB,GZMK,PRF1) / [ ] [ int41BB:ON CD3:ON ] [ comb ]",
    f"Inc(node:proliferation,IFNg,GZMB,GZMK,PRF1) / [ ] [ int41BB:ON CD3:OFF ] [ comb ]", #should show stable
    f"Inc(node:proliferation,IFNg,GZMB,GZMK,PRF1) / [ ] [ int41BB:OFF CD3:ON ] [ comb ]", #should show stable
    #int41BB KI AND CD3 KI increase IL2 higher than int41BB KI
    f"Inc(node:IL2) / [ ] [ int41BB:ON CD3:ON ] [ ]",
    f"Inc(node:IL2) / [ ] [ int41BB:ON CD3:OFF ] [ ]",
    # and int41BB KI does so higher than CD3 KI
    f"Inc(node:IL2) / [ ] [ CD3:ON int41BB:OFF ] [ ]",
    # IL7_L decreases apoptosis
    f"Dec(node:Apoptosis) / [ ] [ IL7_L:ON ] [ ]",
]
output_CD8_list_random_ic = ["Apoptosis","proliferation","IL2","IFNg","GZMB","GZMK","PRF1"]

CD8_list_abTCR_L41BB = [
    #int41BB KI AND CD3 KI decrease Apoptosis to a lower level than CD3 KI or int41BB KI
    f"Dec(node:Apoptosis) / [ ] [ int41BB:ON CD3:ON ] [ ]",
    f"Dec(node:Apoptosis) / [ ] [ int41BB:ON CD3:OFF ] [ ]",
    f"Dec(node:Apoptosis) / [ ] [ int41BB:OFF CD3:ON ] [ ]",
    #int41BB KI AND CD3 KI increase proliferation, IFNg, GZMB, GZMK, PRF1, CD3 KI or int41BB KI have no effect.
    f"Inc(node:proliferation,IFNg,GZMB,GZMK,PRF1) / [ ] [ int41BB:ON CD3:ON ] [ ]",
    f"Inc(node:proliferation,IFNg,GZMB,GZMK,PRF1) / [ ] [ int41BB:ON CD3:OFF ] [ ]", #should show stable
    f"Inc(node:proliferation,IFNg,GZMB,GZMK,PRF1) / [ ] [ int41BB:OFF CD3:ON ] [ ]", #should show stable
    #int41BB KI AND CD3 KI increase proliferation, IFNg, GZMB, GZMK, PRF1, CD3 KI or int41BB KI have no effect. with comb
    f"Inc(node:proliferation,IFNg,GZMB,GZMK,PRF1) / [ ] [ int41BB:ON CD3:ON ] [ comb ]",
    f"Inc(node:proliferation,IFNg,GZMB,GZMK,PRF1) / [ ] [ int41BB:ON CD3:OFF ] [ comb ]", #should show stable
    f"Inc(node:proliferation,IFNg,GZMB,GZMK,PRF1) / [ ] [ int41BB:OFF CD3:ON ] [ comb ]", #should show stable
    #int41BB KI AND CD3 KI increase IL2 higher than int41BB KI
    f"Inc(node:IL2) / [ ] [ int41BB:ON CD3:ON ] [ ]",
    f"Inc(node:IL2) / [ ] [ int41BB:ON CD3:OFF ] [ ]",
    # and int41BB KI does so higher than CD3 KI
    f"Inc(node:IL2) / [ ] [ CD3:ON int41BB:OFF ] [ ]",
]
outptut_CD8_list_abTCR_L41BB = ["Apoptosis","proliferation","IL2","IFNg","GZMB","GZMK","PRF1"]

CD8_CAR41BB_i_c = [
    #THEMIS KO or SHP1 KO increase Apoptosis
    f"Inc(node:Apoptosis) / [ ] [ THEMIS:ON SHP1:ON ] [ ]",
    f"Inc(node:Apoptosis) / [ ] [ THEMIS:OFF SHP1:ON ] [ ]",
    f"Inc(node:Apoptosis) / [ ] [ THEMIS:ON SHP1:OFF ] [ ]",
]

## Simulations CD4 endo

In [4]:
res_phenotypes = tl.MaBoSSEvaluator.querying(CD4_endo_list_phenotypes,cfg,bnd,CD4_endo,["Th1","Th2"])
res_random_ic = tl.MaBoSSEvaluator.querying(CD4_endo_list_random_ic,cfg,bnd,CD4_endo,output_CD4_endo_list_random_ic)
res_th1_ic = tl.MaBoSSEvaluator.querying(CD4_endo_list_th1_ic,cfg,bnd,CD4_endo,output_CD4_endo_list_th1)
res_th2_ic = tl.MaBoSSEvaluator.querying(CD4_endo_list_th2_ic,cfg,bnd,CD4_endo,["EOMES"])
res_abTCR_ic = tl.MaBoSSEvaluator.querying(CD4_endo_list_abTCR_L41BB,cfg,bnd,CD4_endo,output_CD4_endo_list_abTCR_L41BB)
res_CAR41BB_ic = tl.MaBoSSEvaluator.querying(CD4_endo_CAR41BB_i_c,cfg,bnd,CD4_endo,["Apoptosis"])

Evaluations done !
Evaluations done !
Evaluations done !
Evaluations done !
Evaluations done !
Evaluations done !

## Simulation CD8

In [5]:
res_CD8_random = tl.MaBoSSEvaluator.querying(CD8_list_random_ic,cfg,bnd,CD8_endo,output_CD8_list_random_ic)
res_CD8_abTCR = tl.MaBoSSEvaluator.querying(CD8_list_abTCR_L41BB,cfg,bnd,CD8_endo,outptut_CD8_list_abTCR_L41BB)
res_CD8_CAR41BB_ic = tl.MaBoSSEvaluator.querying(CD8_CAR41BB_i_c,cfg,bnd,CD8_endo,["Apoptosis"])

Evaluations done !
Evaluations done !
Evaluations done !

### Results diplay

In [6]:
tl.Visualiser(list_queries=CD4_endo_list_phenotypes, list_of_results=res_phenotypes).display_results_and_queries(title="Phenotypes")
tl.Visualiser(list_queries=CD4_endo_list_random_ic, list_of_results=res_random_ic).display_results_and_queries(title="CD4 endogenous Random IC")
tl.Visualiser(list_queries=CD4_endo_list_th1_ic, list_of_results=res_th1_ic).display_results_and_queries(title="CD4 endogenous Th1 IC")
tl.Visualiser(list_queries=CD4_endo_list_th2_ic, list_of_results=res_th2_ic).display_results_and_queries(title="CD4 endogenous Th2 IC")
tl.Visualiser(list_queries=CD4_endo_list_abTCR_L41BB, list_of_results=res_abTCR_ic).display_results_and_queries(title="CD4 endogenous abTCR L41BB IC")
tl.Visualiser(list_queries=CD4_endo_CAR41BB_i_c, list_of_results=res_CAR41BB_ic).display_results_and_queries(title="CD4 endogenous CAR41BB IC")

Phenotypes
Query 1 : Inc(node:Th1) / [ ] [ IL12_L:OFF IFNG_L:ON IL4_L:ON ] [ ]

,Th1 from master,Th1 from mutation,Difference Th1,Percentage Th1,Increase Th1
0,0.3709,0.4104,0.0395,10.65%,True

Query 2 : Inc(node:Th2) / [ ] [ IL12_L:OFF IFNG_L:OFF IL4_L:ON ] [ ]

,Th2 from master,Th2 from mutation,Difference Th2,Percentage Th2,Increase Th2
0,0.0021,0.0051,0.003,142.86%,True

CD4 endogenous Random IC
Query 1 : Inc(node:GZMB,PRF1,IFNg,TBET,RUNX3,ThPOK,EOMES) / [ ] [ IL12_L:OFF IFNG_L:ON IL4_L:ON ] [ ]

,GZMB from master,GZMB from mutation,Difference GZMB,Percentage GZMB,Increase GZMB,PRF1 from master,PRF1 from mutation,Difference PRF1,Percentage PRF1,Increase PRF1,IFNg from master,IFNg from mutation,Difference IFNg,Percentage IFNg,Increase IFNg,TBET from master,TBET from mutation,Difference TBET,Percentage TBET,Increase TBET,RUNX3 from master,RUNX3 from mutation,Difference RUNX3,Percentage RUNX3,Increase RUNX3,ThPOK from master,ThPOK from mutation,Difference ThPOK,Percentage ThPOK,Increase ThPOK,EOMES from master,EOMES from mutation,Difference EOMES,Percentage EOMES,Increase EOMES
0,0.4468,0.4465,-0.0003,-0.07%,False,0.6749,0.8148,0.1399,20.73%,True,0.4687,0.4732,0.0045,0.96%,True,0.6378,0.7944,0.1566,24.55%,True,0.6353,0.7908,0.1555,24.48%,True,0.6433,0.6495,0.0062,0.96%,True,0.7466,0.8694,0.1228,16.45%,True

Query 2 : Inc(node:GZMB,PRF1,IFNg,TBET,RUNX3,ThPOK,EOMES) / [ ] [ IL12_L:OFF IFNG_L:ON IL4_L:ON ] [ comb ]Inc(node:EOMES) / [ ] [ IL12_L:OFF IFNG_L:OFF IL4_L:ON ] [ ]

,GZMB from master,GZMB from mutation,Difference GZMB,Percentage GZMB,Increase GZMB,"P_cumul(GZMB,PRF1,IFNg,TBET,RUNX3,ThPOK,EOMES) master","P_cumul(GZMB,PRF1,IFNg,TBET,RUNX3,ThPOK,EOMES) mutation",Difference cumul,Percentage cumul,Increase cumul,PRF1 from master,PRF1 from mutation,Difference PRF1,Percentage PRF1,Increase PRF1,IFNg from master,IFNg from mutation,Difference IFNg,Percentage IFNg,Increase IFNg,TBET from master,TBET from mutation,Difference TBET,Percentage TBET,Increase TBET,RUNX3 from master,RUNX3 from mutation,Difference RUNX3,Percentage RUNX3,Increase RUNX3,ThPOK from master,ThPOK from mutation,Difference ThPOK,Percentage ThPOK,Increase ThPOK,EOMES from master,EOMES from mutation,Difference EOMES,Percentage EOMES,Increase EOMES
0,0.4468,0.4465,-0.0003,-0.07%,False,0.2144,0.2229,0.0086,4.00%,True,0.6749,0.8148,0.1399,20.73%,True,0.4687,0.4732,0.0045,0.96%,True,0.6378,0.7944,0.1566,24.55%,True,0.6353,0.7908,0.1555,24.48%,True,0.6433,0.6495,0.0062,0.96%,True,0.7466,0.8694,0.1228,16.45%,True

Query 3 : Dec(node:PRF1,GZMB,GNLY,IFNg) / [ ] [ RUNX3:OFF ] [ ]

,PRF1 from master,PRF1 from mutation,Difference PRF1,Percentage PRF1,Decrease PRF1,GZMB from master,GZMB from mutation,Difference GZMB,Percentage GZMB,Decrease GZMB,GNLY from master,GNLY from mutation,Difference GNLY,Percentage GNLY,Decrease GNLY,IFNg from master,IFNg from mutation,Difference IFNg,Percentage IFNg,Decrease IFNg
0,0.6749,0.1258,-0.5491,-81.36%,True,0.4468,0.1819,-0.2649,-59.29%,True,0.6346,0.0,-0.6346,-100.00%,True,0.4687,0.4652,-0.0035,-0.75%,True

Query 4 : Dec(node:PRF1,GZMB,GNLY,IFNg) / [ ] [ RUNX3:OFF ] [ comb ]Dec(node:PRF1,GZMB,TNFa,GZMK,IFNg,GNLY) / [ ] [ TBET:OFF ] [ ]

,PRF1 from master,PRF1 from mutation,Difference PRF1,Percentage PRF1,Decrease PRF1,"P_cumul(PRF1,GZMB,GNLY,IFNg) master","P_cumul(PRF1,GZMB,GNLY,IFNg) mutation",Difference cumul,Percentage cumul,Decrease cumul,GZMB from master,GZMB from mutation,Difference GZMB,Percentage GZMB,Decrease GZMB,GNLY from master,GNLY from mutation,Difference GNLY,Percentage GNLY,Decrease GNLY,IFNg from master,IFNg from mutation,Difference IFNg,Percentage IFNg,Decrease IFNg
0,0.6749,0.1258,-0.5491,-81.36%,True,0.33,0.0,-0.33,-100.00%,True,0.4468,0.1819,-0.2649,-59.29%,True,0.6346,0.0,-0.6346,-100.00%,True,0.4687,0.4652,-0.0035,-0.75%,True

Query 5 : Dec(node:PRF1,GZMB,TNFa,GZMK,IFNg,GNLY) / [ ] [ TBET:OFF ] [ comb ]

,PRF1 from master,PRF1 from mutation,Difference PRF1,Percentage PRF1,Decrease PRF1,"P_cumul(PRF1,GZMB,TNFa,GZMK,IFNg,GNLY) master","P_cumul(PRF1,GZMB,TNFa,GZMK,IFNg,GNLY) mutation",Difference cumul,Percentage cumul,Decrease cumul,GZMB from master,GZMB from mutation,Difference GZMB,Percentage GZMB,Decrease GZMB,TNFa from master,TNFa from mutation,Difference TNFa,Percentage TNFa,Decrease TNFa,GZMK from master,GZMK from mutation,Difference GZMK,Percentage GZMK,Decrease GZMK,IFNg from master,IFNg from mutation,Difference IFNg,Percentage IFNg,Decrease IFNg,GNLY from master,GNLY from mutation,Difference GNLY,Percentage GNLY,Decrease GNLY
0,0.6749,0.1074,-0.5675,-84.09%,True,0.1242,0.0,-0.1242,-100.00%,True,0.4468,0.1541,-0.2927,-65.51%,True,0.2611,0.2613,0.0002,0.08%,False,0.6783,0.1075,-0.5708,-84.15%,True,0.4687,0.2621,-0.2066,-44.08%,True,0.6346,0.0,-0.6346,-100.00%,True

Query 6 : Inc(node:PRF1,GZMB) / [ ] [ EOMES:OFF ] [ ]

,PRF1 from master,PRF1 from mutation,Difference PRF1,Percentage PRF1,Increase PRF1,GZMB from master,GZMB from mutation,Difference GZMB,Percentage GZMB,Increase GZMB
0,0.6749,0.674,-0.0009,-0.13%,False,0.4468,0.4387,-0.0081,-1.81%,False

Query 7 : Inc(node:PRF1,GZMB) / [ ] [ ThPOK:OFF ] [ ]

,PRF1 from master,PRF1 from mutation,Difference PRF1,Percentage PRF1,Increase PRF1,GZMB from master,GZMB from mutation,Difference GZMB,Percentage GZMB,Increase GZMB
0,0.6749,0.7455,0.0706,10.46%,True,0.4468,0.5604,0.1136,25.43%,True

Query 8 : Inc(node:PRF1,GZMB) / [ ] [ EOMES:OFF ] [ comb ]

,PRF1 from master,PRF1 from mutation,Difference PRF1,Percentage PRF1,Increase PRF1,"P_cumul(PRF1,GZMB) master","P_cumul(PRF1,GZMB) mutation",Difference cumul,Percentage cumul,Increase cumul,GZMB from master,GZMB from mutation,Difference GZMB,Percentage GZMB,Increase GZMB
0,0.6749,0.674,-0.0009,-0.13%,False,0.3916,0.3842,-0.0074,-1.89%,False,0.4468,0.4387,-0.0081,-1.81%,False

Query 9 : Inc(node:PRF1,GZMB) / [ ] [ ThPOK:OFF ] [ comb ]

,PRF1 from master,PRF1 from mutation,Difference PRF1,Percentage PRF1,Increase PRF1,"P_cumul(PRF1,GZMB) master","P_cumul(PRF1,GZMB) mutation",Difference cumul,Percentage cumul,Increase cumul,GZMB from master,GZMB from mutation,Difference GZMB,Percentage GZMB,Increase GZMB
0,0.6749,0.7455,0.0706,10.46%,True,0.3916,0.4178,0.0262,6.70%,True,0.4468,0.5604,0.1136,25.43%,True

Query 10 : Dec(node:Apoptosis) / [ ] [ int41BB:ON CD3:ON ] [ ]

,Apoptosis from master,Apoptosis from mutation,Difference Apoptosis,Percentage Apoptosis,Decrease Apoptosis
0,0.2654,0.3097,0.0443,16.69%,False

Query 11 : Dec(node:Apoptosis) / [ ] [ int41BB:ON CD3:OFF ] [ ]

,Apoptosis from master,Apoptosis from mutation,Difference Apoptosis,Percentage Apoptosis,Decrease Apoptosis
0,0.2654,0.26,-0.0054,-2.03%,True

Query 12 : Dec(node:Apoptosis) / [ ] [ int41BB:OFF CD3:ON ] [ ]

,Apoptosis from master,Apoptosis from mutation,Difference Apoptosis,Percentage Apoptosis,Decrease Apoptosis
0,0.2654,0.3102,0.0448,16.88%,False

Query 13 : Inc(node:proliferation,IFNg,GZMB,GZMK,PRF1) / [ ] [ int41BB:ON CD3:ON ] [ ]

,proliferation from master,proliferation from mutation,Difference proliferation,Percentage proliferation,Increase proliferation,IFNg from master,IFNg from mutation,Difference IFNg,Percentage IFNg,Increase IFNg,GZMB from master,GZMB from mutation,Difference GZMB,Percentage GZMB,Increase GZMB,GZMK from master,GZMK from mutation,Difference GZMK,Percentage GZMK,Increase GZMK,PRF1 from master,PRF1 from mutation,Difference PRF1,Percentage PRF1,Increase PRF1
0,0.7059,0.6058,-0.1001,-14.18%,False,0.4687,0.4927,0.024,5.12%,True,0.4468,0.3644,-0.0824,-18.44%,False,0.6783,0.6921,0.0138,2.03%,True,0.6749,0.6918,0.0169,2.50%,True

Query 14 : Inc(node:proliferation,IFNg,GZMB,GZMK,PRF1) / [ ] [ int41BB:ON CD3:OFF ] [ ]

,proliferation from master,proliferation from mutation,Difference proliferation,Percentage proliferation,Increase proliferation,IFNg from master,IFNg from mutation,Difference IFNg,Percentage IFNg,Increase IFNg,GZMB from master,GZMB from mutation,Difference GZMB,Percentage GZMB,Increase GZMB,GZMK from master,GZMK from mutation,Difference GZMK,Percentage GZMK,Increase GZMK,PRF1 from master,PRF1 from mutation,Difference PRF1,Percentage PRF1,Increase PRF1
0,0.7059,0.7083,0.0024,0.34%,True,0.4687,0.4164,-0.0523,-11.16%,False,0.4468,0.4408,-0.006,-1.34%,False,0.6783,0.6587,-0.0196,-2.89%,False,0.6749,0.6558,-0.0191,-2.83%,False

Query 15 : Inc(node:proliferation,IFNg,GZMB,GZMK,PRF1) / [ ] [ int41BB:OFF CD3:ON ] [ ]

,proliferation from master,proliferation from mutation,Difference proliferation,Percentage proliferation,Increase proliferation,IFNg from master,IFNg from mutation,Difference IFNg,Percentage IFNg,Increase IFNg,GZMB from master,GZMB from mutation,Difference GZMB,Percentage GZMB,Increase GZMB,GZMK from master,GZMK from mutation,Difference GZMK,Percentage GZMK,Increase GZMK,PRF1 from master,PRF1 from mutation,Difference PRF1,Percentage PRF1,Increase PRF1
0,0.7059,0.6034,-0.1025,-14.52%,False,0.4687,0.4888,0.0201,4.29%,True,0.4468,0.3652,-0.0816,-18.26%,False,0.6783,0.6937,0.0154,2.27%,True,0.6749,0.6924,0.0175,2.59%,True

Query 16 : Inc(node:proliferation,IFNg,GZMB,GZMK,PRF1) / [ ] [ int41BB:ON CD3:ON ] [ comb ]

,proliferation from master,proliferation from mutation,Difference proliferation,Percentage proliferation,Increase proliferation,"P_cumul(proliferation,IFNg,GZMB,GZMK,PRF1) master","P_cumul(proliferation,IFNg,GZMB,GZMK,PRF1) mutation",Difference cumul,Percentage cumul,Increase cumul,IFNg from master,IFNg from mutation,Difference IFNg,Percentage IFNg,Increase IFNg,GZMB from master,GZMB from mutation,Difference GZMB,Percentage GZMB,Increase GZMB,GZMK from master,GZMK from mutation,Difference GZMK,Percentage GZMK,Increase GZMK,PRF1 from master,PRF1 from mutation,Difference PRF1,Percentage PRF1,Increase PRF1
0,0.7059,0.6058,-0.1001,-14.18%,False,0.3449,0.2734,-0.0715,-20.72%,False,0.4687,0.4927,0.024,5.12%,True,0.4468,0.3644,-0.0824,-18.44%,False,0.6783,0.6921,0.0138,2.03%,True,0.6749,0.6918,0.0169,2.50%,True

Query 17 : Inc(node:proliferation,IFNg,GZMB,GZMK,PRF1) / [ ] [ int41BB:ON CD3:OFF ] [ comb ]

,proliferation from master,proliferation from mutation,Difference proliferation,Percentage proliferation,Increase proliferation,"P_cumul(proliferation,IFNg,GZMB,GZMK,PRF1) master","P_cumul(proliferation,IFNg,GZMB,GZMK,PRF1) mutation",Difference cumul,Percentage cumul,Increase cumul,IFNg from master,IFNg from mutation,Difference IFNg,Percentage IFNg,Increase IFNg,GZMB from master,GZMB from mutation,Difference GZMB,Percentage GZMB,Increase GZMB,GZMK from master,GZMK from mutation,Difference GZMK,Percentage GZMK,Increase GZMK,PRF1 from master,PRF1 from mutation,Difference PRF1,Percentage PRF1,Increase PRF1
0,0.7059,0.7083,0.0024,0.34%,True,0.3449,0.3528,0.008,2.32%,True,0.4687,0.4164,-0.0523,-11.16%,False,0.4468,0.4408,-0.006,-1.34%,False,0.6783,0.6587,-0.0196,-2.89%,False,0.6749,0.6558,-0.0191,-2.83%,False

Query 18 : Inc(node:proliferation,IFNg,GZMB,GZMK,PRF1) / [ ] [ int41BB:OFF CD3:ON ] [ comb ]

,proliferation from master,proliferation from mutation,Difference proliferation,Percentage proliferation,Increase proliferation,"P_cumul(proliferation,IFNg,GZMB,GZMK,PRF1) master","P_cumul(proliferation,IFNg,GZMB,GZMK,PRF1) mutation",Difference cumul,Percentage cumul,Increase cumul,IFNg from master,IFNg from mutation,Difference IFNg,Percentage IFNg,Increase IFNg,GZMB from master,GZMB from mutation,Difference GZMB,Percentage GZMB,Increase GZMB,GZMK from master,GZMK from mutation,Difference GZMK,Percentage GZMK,Increase GZMK,PRF1 from master,PRF1 from mutation,Difference PRF1,Percentage PRF1,Increase PRF1
0,0.7059,0.6034,-0.1025,-14.52%,False,0.3449,0.2732,-0.0716,-20.77%,False,0.4687,0.4888,0.0201,4.29%,True,0.4468,0.3652,-0.0816,-18.26%,False,0.6783,0.6937,0.0154,2.27%,True,0.6749,0.6924,0.0175,2.59%,True

Query 19 : Inc(node:IL2) / [ ] [ int41BB:ON CD3:ON ] [ ]

,IL2 from master,IL2 from mutation,Difference IL2,Percentage IL2,Increase IL2
0,0.1918,0.4233,0.2315,120.70%,True

Query 20 : Inc(node:IL2) / [ ] [ int41BB:ON CD3:OFF ] [ ]

,IL2 from master,IL2 from mutation,Difference IL2,Percentage IL2,Increase IL2
0,0.1918,0.0,-0.1918,-100.00%,False

Query 21 : Inc(node:IL2) / [ ] [ CD3:ON int41BB:OFF ] [ ]

,IL2 from master,IL2 from mutation,Difference IL2,Percentage IL2,Increase IL2
0,0.1918,0.4186,0.2268,118.25%,True

Query 22 : Dec(node:Apoptosis) / [ ] [ IL7_L:ON ] [ ]

,Apoptosis from master,Apoptosis from mutation,Difference Apoptosis,Percentage Apoptosis,Decrease Apoptosis
0,0.2654,0.2595,-0.0059,-2.22%,True

Query 23 : Inc(node:TBET,BLIMP1,EOMES,GZMB,PRF1) / [ ] [ IL2_L:ON IFNG_L:OFF ] [ ]

,TBET from master,TBET from mutation,Difference TBET,Percentage TBET,Increase TBET,BLIMP1 from master,BLIMP1 from mutation,Difference BLIMP1,Percentage BLIMP1,Increase BLIMP1,EOMES from master,EOMES from mutation,Difference EOMES,Percentage EOMES,Increase EOMES,GZMB from master,GZMB from mutation,Difference GZMB,Percentage GZMB,Increase GZMB,PRF1 from master,PRF1 from mutation,Difference PRF1,Percentage PRF1,Increase PRF1
0,0.6378,0.5718,-0.066,-10.35%,False,0.7484,0.7547,0.0063,0.84%,True,0.7466,0.7533,0.0067,0.90%,True,0.4468,0.467,0.0202,4.52%,True,0.6749,0.6361,-0.0388,-5.75%,False

Query 24 : Inc(node:TBET,BLIMP1,EOMES,GZMB,PRF1) / [ ] [ IFNG_L:ON IL2_L:OFF ] [ ]

,TBET from master,TBET from mutation,Difference TBET,Percentage TBET,Increase TBET,BLIMP1 from master,BLIMP1 from mutation,Difference BLIMP1,Percentage BLIMP1,Increase BLIMP1,EOMES from master,EOMES from mutation,Difference EOMES,Percentage EOMES,Increase EOMES,GZMB from master,GZMB from mutation,Difference GZMB,Percentage GZMB,Increase GZMB,PRF1 from master,PRF1 from mutation,Difference PRF1,Percentage PRF1,Increase PRF1
0,0.6378,0.7276,0.0898,14.08%,True,0.7484,0.7825,0.0341,4.56%,True,0.7466,0.7813,0.0347,4.65%,True,0.4468,0.4412,-0.0056,-1.25%,False,0.6749,0.7438,0.0689,10.21%,True

Query 25 : Inc(node:TBET,BLIMP1,EOMES,GZMB,PRF1) / [ ] [ IFNG_L:ON IL2_L:ON ] [ ]

,TBET from master,TBET from mutation,Difference TBET,Percentage TBET,Increase TBET,BLIMP1 from master,BLIMP1 from mutation,Difference BLIMP1,Percentage BLIMP1,Increase BLIMP1,EOMES from master,EOMES from mutation,Difference EOMES,Percentage EOMES,Increase EOMES,GZMB from master,GZMB from mutation,Difference GZMB,Percentage GZMB,Increase GZMB,PRF1 from master,PRF1 from mutation,Difference PRF1,Percentage PRF1,Increase PRF1
0,0.6378,0.784,0.1462,22.92%,True,0.7484,0.8781,0.1297,17.33%,True,0.7466,0.8769,0.1303,17.45%,True,0.4468,0.5484,0.1016,22.74%,True,0.6749,0.8159,0.141,20.89%,True

Query 26 : Inc(node:TBET,BLIMP1,EOMES,GZMB,PRF1) / [ ] [ IL2_L:ON IFNG_L:OFF ] [ comb ]

,TBET from master,TBET from mutation,Difference TBET,Percentage TBET,Increase TBET,"P_cumul(TBET,BLIMP1,EOMES,GZMB,PRF1) master","P_cumul(TBET,BLIMP1,EOMES,GZMB,PRF1) mutation",Difference cumul,Percentage cumul,Increase cumul,BLIMP1 from master,BLIMP1 from mutation,Difference BLIMP1,Percentage BLIMP1,Increase BLIMP1,EOMES from master,EOMES from mutation,Difference EOMES,Percentage EOMES,Increase EOMES,GZMB from master,GZMB from mutation,Difference GZMB,Percentage GZMB,Increase GZMB,PRF1 from master,PRF1 from mutation,Difference PRF1,Percentage PRF1,Increase PRF1
0,0.6378,0.5718,-0.066,-10.35%,False,0.376,0.3797,0.0036,0.97%,True,0.7484,0.7547,0.0063,0.84%,True,0.7466,0.7533,0.0067,0.90%,True,0.4468,0.467,0.0202,4.52%,True,0.6749,0.6361,-0.0388,-5.75%,False

Query 27 : Inc(node:TBET,BLIMP1,EOMES,GZMB,PRF1) / [ ] [ IFNG_L:ON IL2_L:OFF ] [ comb ]

,TBET from master,TBET from mutation,Difference TBET,Percentage TBET,Increase TBET,"P_cumul(TBET,BLIMP1,EOMES,GZMB,PRF1) master","P_cumul(TBET,BLIMP1,EOMES,GZMB,PRF1) mutation",Difference cumul,Percentage cumul,Increase cumul,BLIMP1 from master,BLIMP1 from mutation,Difference BLIMP1,Percentage BLIMP1,Increase BLIMP1,EOMES from master,EOMES from mutation,Difference EOMES,Percentage EOMES,Increase EOMES,GZMB from master,GZMB from mutation,Difference GZMB,Percentage GZMB,Increase GZMB,PRF1 from master,PRF1 from mutation,Difference PRF1,Percentage PRF1,Increase PRF1
0,0.6378,0.7276,0.0898,14.08%,True,0.376,0.3954,0.0193,5.14%,True,0.7484,0.7825,0.0341,4.56%,True,0.7466,0.7813,0.0347,4.65%,True,0.4468,0.4412,-0.0056,-1.25%,False,0.6749,0.7438,0.0689,10.21%,True

Query 28 : Inc(node:TBET,BLIMP1,EOMES,GZMB,PRF1) / [ ] [ IFNG_L:ON IL2_L:ON ] [ comb ]

,TBET from master,TBET from mutation,Difference TBET,Percentage TBET,Increase TBET,"P_cumul(TBET,BLIMP1,EOMES,GZMB,PRF1) master","P_cumul(TBET,BLIMP1,EOMES,GZMB,PRF1) mutation",Difference cumul,Percentage cumul,Increase cumul,BLIMP1 from master,BLIMP1 from mutation,Difference BLIMP1,Percentage BLIMP1,Increase BLIMP1,EOMES from master,EOMES from mutation,Difference EOMES,Percentage EOMES,Increase EOMES,GZMB from master,GZMB from mutation,Difference GZMB,Percentage GZMB,Increase GZMB,PRF1 from master,PRF1 from mutation,Difference PRF1,Percentage PRF1,Increase PRF1
0,0.6378,0.784,0.1462,22.92%,True,0.376,0.5045,0.1285,34.17%,True,0.7484,0.8781,0.1297,17.33%,True,0.7466,0.8769,0.1303,17.45%,True,0.4468,0.5484,0.1016,22.74%,True,0.6749,0.8159,0.141,20.89%,True

Query 29 : Inc(node:Treg,FOXP3,IL2RA,IL10) / [ ] [ IL2_L:ON TGFB_L:ON ] [ ]

,Treg from master,Treg from mutation,Difference Treg,Percentage Treg,Increase Treg,FOXP3 from master,FOXP3 from mutation,Difference FOXP3,Percentage FOXP3,Increase FOXP3,IL2RA from master,IL2RA from mutation,Difference IL2RA,Percentage IL2RA,Increase IL2RA,IL10 from master,IL10 from mutation,Difference IL10,Percentage IL10,Increase IL10
0,0.0808,0.1873,0.1065,131.81%,True,0.1362,0.2794,0.1432,105.14%,True,0.546,0.6567,0.1107,20.27%,True,0.3237,0.5032,0.1795,55.45%,True

Query 30 : Inc(node:Treg,FOXP3,IL2RA,IL10) / [ ] [ IL2_L:ON TGFB_L:ON ] [ comb ]

,Treg from master,Treg from mutation,Difference Treg,Percentage Treg,Increase Treg,"P_cumul(Treg,FOXP3,IL2RA,IL10) master","P_cumul(Treg,FOXP3,IL2RA,IL10) mutation",Difference cumul,Percentage cumul,Increase cumul,FOXP3 from master,FOXP3 from mutation,Difference FOXP3,Percentage FOXP3,Increase FOXP3,IL2RA from master,IL2RA from mutation,Difference IL2RA,Percentage IL2RA,Increase IL2RA,IL10 from master,IL10 from mutation,Difference IL10,Percentage IL10,Increase IL10
0,0.0808,0.1873,0.1065,131.81%,True,0.0797,0.185,0.1053,132.23%,True,0.1362,0.2794,0.1432,105.14%,True,0.546,0.6567,0.1107,20.27%,True,0.3237,0.5032,0.1795,55.45%,True

CD4 endogenous Th1 IC
Query 1 : Inc(node:GZMB,PRF1,IFNg,TBET,RUNX3,ThPOK,EOMES) / [ ] [ IFNG_L:ON IL12_L:ON IL4_L:OFF ] [ ]

,GZMB from master,GZMB from mutation,Difference GZMB,Percentage GZMB,Increase GZMB,PRF1 from master,PRF1 from mutation,Difference PRF1,Percentage PRF1,Increase PRF1,IFNg from master,IFNg from mutation,Difference IFNg,Percentage IFNg,Increase IFNg,TBET from master,TBET from mutation,Difference TBET,Percentage TBET,Increase TBET,RUNX3 from master,RUNX3 from mutation,Difference RUNX3,Percentage RUNX3,Increase RUNX3,ThPOK from master,ThPOK from mutation,Difference ThPOK,Percentage ThPOK,Increase ThPOK,EOMES from master,EOMES from mutation,Difference EOMES,Percentage EOMES,Increase EOMES
0,0.4468,0.5528,0.106,23.72%,True,0.6749,0.7596,0.0847,12.55%,True,0.4688,0.5387,0.0699,14.91%,True,0.6378,0.7392,0.1014,15.90%,True,0.6353,0.7392,0.1039,16.35%,True,0.6433,0.6187,-0.0246,-3.82%,False,0.7466,0.791,0.0444,5.95%,True

Query 2 : Inc(node:GZMB,PRF1,IFNg,TBET,RUNX3,ThPOK,EOMES) / [ ] [ IFNG_L:ON IL12_L:ON IL4_L:OFF ] [ comb ]

,GZMB from master,GZMB from mutation,Difference GZMB,Percentage GZMB,Increase GZMB,"P_cumul(GZMB,PRF1,IFNg,TBET,RUNX3,ThPOK,EOMES) master","P_cumul(GZMB,PRF1,IFNg,TBET,RUNX3,ThPOK,EOMES) mutation",Difference cumul,Percentage cumul,Increase cumul,PRF1 from master,PRF1 from mutation,Difference PRF1,Percentage PRF1,Increase PRF1,IFNg from master,IFNg from mutation,Difference IFNg,Percentage IFNg,Increase IFNg,TBET from master,TBET from mutation,Difference TBET,Percentage TBET,Increase TBET,RUNX3 from master,RUNX3 from mutation,Difference RUNX3,Percentage RUNX3,Increase RUNX3,ThPOK from master,ThPOK from mutation,Difference ThPOK,Percentage ThPOK,Increase ThPOK,EOMES from master,EOMES from mutation,Difference EOMES,Percentage EOMES,Increase EOMES
0,0.4468,0.5528,0.106,23.72%,True,0.2144,0.2926,0.0782,36.48%,True,0.6749,0.7596,0.0847,12.55%,True,0.4688,0.5387,0.0699,14.91%,True,0.6378,0.7392,0.1014,15.90%,True,0.6353,0.7392,0.1039,16.35%,True,0.6433,0.6187,-0.0246,-3.82%,False,0.7466,0.791,0.0444,5.95%,True

Query 3 : Dec(node:PRF1,GZMB,GNLY,IFNg) / [ ] [ RUNX3:OFF ] [ ]

,PRF1 from master,PRF1 from mutation,Difference PRF1,Percentage PRF1,Decrease PRF1,GZMB from master,GZMB from mutation,Difference GZMB,Percentage GZMB,Decrease GZMB,GNLY from master,GNLY from mutation,Difference GNLY,Percentage GNLY,Decrease GNLY,IFNg from master,IFNg from mutation,Difference IFNg,Percentage IFNg,Decrease IFNg
0,0.6749,0.1258,-0.5491,-81.36%,True,0.4468,0.1819,-0.2649,-59.29%,True,0.6346,0.0,-0.6346,-100.00%,True,0.4688,0.4652,-0.0036,-0.77%,True

Query 4 : Dec(node:PRF1,GZMB,GNLY,IFNg) / [ ] [ RUNX3:OFF ] [ comb ]

,PRF1 from master,PRF1 from mutation,Difference PRF1,Percentage PRF1,Decrease PRF1,"P_cumul(PRF1,GZMB,GNLY,IFNg) master","P_cumul(PRF1,GZMB,GNLY,IFNg) mutation",Difference cumul,Percentage cumul,Decrease cumul,GZMB from master,GZMB from mutation,Difference GZMB,Percentage GZMB,Decrease GZMB,GNLY from master,GNLY from mutation,Difference GNLY,Percentage GNLY,Decrease GNLY,IFNg from master,IFNg from mutation,Difference IFNg,Percentage IFNg,Decrease IFNg
0,0.6749,0.1258,-0.5491,-81.36%,True,0.3301,0.0,-0.3301,-100.00%,True,0.4468,0.1819,-0.2649,-59.29%,True,0.6346,0.0,-0.6346,-100.00%,True,0.4688,0.4652,-0.0036,-0.77%,True

Query 5 : Dec(node:PRF1,GZMB,TNFa,GZMK,IFNg,GNLY) / [ ] [ TBET:OFF ] [ ]

,PRF1 from master,PRF1 from mutation,Difference PRF1,Percentage PRF1,Decrease PRF1,GZMB from master,GZMB from mutation,Difference GZMB,Percentage GZMB,Decrease GZMB,TNFa from master,TNFa from mutation,Difference TNFa,Percentage TNFa,Decrease TNFa,GZMK from master,GZMK from mutation,Difference GZMK,Percentage GZMK,Decrease GZMK,IFNg from master,IFNg from mutation,Difference IFNg,Percentage IFNg,Decrease IFNg,GNLY from master,GNLY from mutation,Difference GNLY,Percentage GNLY,Decrease GNLY
0,0.6749,0.1074,-0.5675,-84.09%,True,0.4468,0.1541,-0.2927,-65.51%,True,0.2611,0.2613,0.0002,0.08%,False,0.6783,0.1075,-0.5708,-84.15%,True,0.4688,0.2621,-0.2067,-44.09%,True,0.6346,0.0,-0.6346,-100.00%,True

Query 6 : Dec(node:PRF1,GZMB,TNFa,GZMK,IFNg,GNLY) / [ ] [ TBET:OFF ] [ comb ]

,PRF1 from master,PRF1 from mutation,Difference PRF1,Percentage PRF1,Decrease PRF1,"P_cumul(PRF1,GZMB,TNFa,GZMK,IFNg,GNLY) master","P_cumul(PRF1,GZMB,TNFa,GZMK,IFNg,GNLY) mutation",Difference cumul,Percentage cumul,Decrease cumul,GZMB from master,GZMB from mutation,Difference GZMB,Percentage GZMB,Decrease GZMB,TNFa from master,TNFa from mutation,Difference TNFa,Percentage TNFa,Decrease TNFa,GZMK from master,GZMK from mutation,Difference GZMK,Percentage GZMK,Decrease GZMK,IFNg from master,IFNg from mutation,Difference IFNg,Percentage IFNg,Decrease IFNg,GNLY from master,GNLY from mutation,Difference GNLY,Percentage GNLY,Decrease GNLY
0,0.6749,0.1074,-0.5675,-84.09%,True,0.1242,0.0,-0.1242,-100.00%,True,0.4468,0.1541,-0.2927,-65.51%,True,0.2611,0.2613,0.0002,0.08%,False,0.6783,0.1075,-0.5708,-84.15%,True,0.4688,0.2621,-0.2067,-44.09%,True,0.6346,0.0,-0.6346,-100.00%,True

Query 7 : Inc(node:PRF1,GZMB) / [ ] [ EOMES:OFF ] [ ]

,PRF1 from master,PRF1 from mutation,Difference PRF1,Percentage PRF1,Increase PRF1,GZMB from master,GZMB from mutation,Difference GZMB,Percentage GZMB,Increase GZMB
0,0.6749,0.674,-0.0009,-0.13%,False,0.4468,0.4387,-0.0081,-1.81%,False

Query 8 : Inc(node:PRF1,GZMB) / [ ] [ ThPOK:OFF ] [ ]

,PRF1 from master,PRF1 from mutation,Difference PRF1,Percentage PRF1,Increase PRF1,GZMB from master,GZMB from mutation,Difference GZMB,Percentage GZMB,Increase GZMB
0,0.6749,0.7455,0.0706,10.46%,True,0.4468,0.5604,0.1136,25.43%,True

Query 9 : Inc(node:PRF1,GZMB) / [ ] [ EOMES:OFF ] [ comb ]

,PRF1 from master,PRF1 from mutation,Difference PRF1,Percentage PRF1,Increase PRF1,"P_cumul(PRF1,GZMB) master","P_cumul(PRF1,GZMB) mutation",Difference cumul,Percentage cumul,Increase cumul,GZMB from master,GZMB from mutation,Difference GZMB,Percentage GZMB,Increase GZMB
0,0.6749,0.674,-0.0009,-0.13%,False,0.3916,0.3842,-0.0074,-1.89%,False,0.4468,0.4387,-0.0081,-1.81%,False

Query 10 : Inc(node:PRF1,GZMB) / [ ] [ ThPOK:OFF ] [ comb ]

,PRF1 from master,PRF1 from mutation,Difference PRF1,Percentage PRF1,Increase PRF1,"P_cumul(PRF1,GZMB) master","P_cumul(PRF1,GZMB) mutation",Difference cumul,Percentage cumul,Increase cumul,GZMB from master,GZMB from mutation,Difference GZMB,Percentage GZMB,Increase GZMB
0,0.6749,0.7455,0.0706,10.46%,True,0.3916,0.4178,0.0262,6.70%,True,0.4468,0.5604,0.1136,25.43%,True

CD4 endogenous Th2 IC
Query 1 : Inc(node:EOMES) / [ ] [ IL4_L:ON IFNG_L:ON IL12_L:ON ] [ ]

,EOMES from master,EOMES from mutation,Difference EOMES,Percentage EOMES,Increase EOMES
0,0.7466,0.8688,0.1222,16.37%,True

CD4 endogenous abTCR L41BB IC
Query 1 : Dec(node:Apoptosis) / [ ] [ int41BB:ON CD3:ON ] [ ]

,Apoptosis from master,Apoptosis from mutation,Difference Apoptosis,Percentage Apoptosis,Decrease Apoptosis
0,0.2654,0.3097,0.0443,16.69%,False

Query 2 : Dec(node:Apoptosis) / [ ] [ int41BB:ON CD3:OFF ] [ ]

,Apoptosis from master,Apoptosis from mutation,Difference Apoptosis,Percentage Apoptosis,Decrease Apoptosis
0,0.2654,0.26,-0.0054,-2.03%,True

Query 3 : Dec(node:Apoptosis) / [ ] [ int41BB:OFF CD3:ON ] [ ]

,Apoptosis from master,Apoptosis from mutation,Difference Apoptosis,Percentage Apoptosis,Decrease Apoptosis
0,0.2654,0.3102,0.0448,16.88%,False

Query 4 : Inc(node:proliferation,IFNg,GZMB,GZMK,PRF1) / [ ] [ int41BB:ON CD3:ON ] [ ]

,proliferation from master,proliferation from mutation,Difference proliferation,Percentage proliferation,Increase proliferation,IFNg from master,IFNg from mutation,Difference IFNg,Percentage IFNg,Increase IFNg,GZMB from master,GZMB from mutation,Difference GZMB,Percentage GZMB,Increase GZMB,GZMK from master,GZMK from mutation,Difference GZMK,Percentage GZMK,Increase GZMK,PRF1 from master,PRF1 from mutation,Difference PRF1,Percentage PRF1,Increase PRF1
0,0.7059,0.6058,-0.1001,-14.18%,False,0.4687,0.4927,0.024,5.12%,True,0.4468,0.3644,-0.0824,-18.44%,False,0.6783,0.6921,0.0138,2.03%,True,0.6749,0.6918,0.0169,2.50%,True

Query 5 : Inc(node:proliferation,IFNg,GZMB,GZMK,PRF1) / [ ] [ int41BB:ON CD3:OFF ] [ ]

,proliferation from master,proliferation from mutation,Difference proliferation,Percentage proliferation,Increase proliferation,IFNg from master,IFNg from mutation,Difference IFNg,Percentage IFNg,Increase IFNg,GZMB from master,GZMB from mutation,Difference GZMB,Percentage GZMB,Increase GZMB,GZMK from master,GZMK from mutation,Difference GZMK,Percentage GZMK,Increase GZMK,PRF1 from master,PRF1 from mutation,Difference PRF1,Percentage PRF1,Increase PRF1
0,0.7059,0.7083,0.0024,0.34%,True,0.4687,0.4164,-0.0523,-11.16%,False,0.4468,0.4408,-0.006,-1.34%,False,0.6783,0.6587,-0.0196,-2.89%,False,0.6749,0.6558,-0.0191,-2.83%,False

Query 6 : Inc(node:proliferation,IFNg,GZMB,GZMK,PRF1) / [ ] [ int41BB:OFF CD3:ON ] [ ]

,proliferation from master,proliferation from mutation,Difference proliferation,Percentage proliferation,Increase proliferation,IFNg from master,IFNg from mutation,Difference IFNg,Percentage IFNg,Increase IFNg,GZMB from master,GZMB from mutation,Difference GZMB,Percentage GZMB,Increase GZMB,GZMK from master,GZMK from mutation,Difference GZMK,Percentage GZMK,Increase GZMK,PRF1 from master,PRF1 from mutation,Difference PRF1,Percentage PRF1,Increase PRF1
0,0.7059,0.6034,-0.1025,-14.52%,False,0.4687,0.4888,0.0201,4.29%,True,0.4468,0.3652,-0.0816,-18.26%,False,0.6783,0.6937,0.0154,2.27%,True,0.6749,0.6924,0.0175,2.59%,True

Query 7 : Inc(node:proliferation,IFNg,GZMB,GZMK,PRF1) / [ ] [ int41BB:ON CD3:ON ] [ comb ]

,proliferation from master,proliferation from mutation,Difference proliferation,Percentage proliferation,Increase proliferation,"P_cumul(proliferation,IFNg,GZMB,GZMK,PRF1) master","P_cumul(proliferation,IFNg,GZMB,GZMK,PRF1) mutation",Difference cumul,Percentage cumul,Increase cumul,IFNg from master,IFNg from mutation,Difference IFNg,Percentage IFNg,Increase IFNg,GZMB from master,GZMB from mutation,Difference GZMB,Percentage GZMB,Increase GZMB,GZMK from master,GZMK from mutation,Difference GZMK,Percentage GZMK,Increase GZMK,PRF1 from master,PRF1 from mutation,Difference PRF1,Percentage PRF1,Increase PRF1
0,0.7059,0.6058,-0.1001,-14.18%,False,0.3449,0.2734,-0.0715,-20.72%,False,0.4687,0.4927,0.024,5.12%,True,0.4468,0.3644,-0.0824,-18.44%,False,0.6783,0.6921,0.0138,2.03%,True,0.6749,0.6918,0.0169,2.50%,True

Query 8 : Inc(node:proliferation,IFNg,GZMB,GZMK,PRF1) / [ ] [ int41BB:ON CD3:OFF ] [ comb ]

,proliferation from master,proliferation from mutation,Difference proliferation,Percentage proliferation,Increase proliferation,"P_cumul(proliferation,IFNg,GZMB,GZMK,PRF1) master","P_cumul(proliferation,IFNg,GZMB,GZMK,PRF1) mutation",Difference cumul,Percentage cumul,Increase cumul,IFNg from master,IFNg from mutation,Difference IFNg,Percentage IFNg,Increase IFNg,GZMB from master,GZMB from mutation,Difference GZMB,Percentage GZMB,Increase GZMB,GZMK from master,GZMK from mutation,Difference GZMK,Percentage GZMK,Increase GZMK,PRF1 from master,PRF1 from mutation,Difference PRF1,Percentage PRF1,Increase PRF1
0,0.7059,0.7083,0.0024,0.34%,True,0.3449,0.3528,0.008,2.32%,True,0.4687,0.4164,-0.0523,-11.16%,False,0.4468,0.4408,-0.006,-1.34%,False,0.6783,0.6587,-0.0196,-2.89%,False,0.6749,0.6558,-0.0191,-2.83%,False

Query 9 : Inc(node:proliferation,IFNg,GZMB,GZMK,PRF1) / [ ] [ int41BB:OFF CD3:ON ] [ comb ]

,proliferation from master,proliferation from mutation,Difference proliferation,Percentage proliferation,Increase proliferation,"P_cumul(proliferation,IFNg,GZMB,GZMK,PRF1) master","P_cumul(proliferation,IFNg,GZMB,GZMK,PRF1) mutation",Difference cumul,Percentage cumul,Increase cumul,IFNg from master,IFNg from mutation,Difference IFNg,Percentage IFNg,Increase IFNg,GZMB from master,GZMB from mutation,Difference GZMB,Percentage GZMB,Increase GZMB,GZMK from master,GZMK from mutation,Difference GZMK,Percentage GZMK,Increase GZMK,PRF1 from master,PRF1 from mutation,Difference PRF1,Percentage PRF1,Increase PRF1
0,0.7059,0.6034,-0.1025,-14.52%,False,0.3449,0.2732,-0.0716,-20.77%,False,0.4687,0.4888,0.0201,4.29%,True,0.4468,0.3652,-0.0816,-18.26%,False,0.6783,0.6937,0.0154,2.27%,True,0.6749,0.6924,0.0175,2.59%,True

Query 10 : Inc(node:IL2) / [ ] [ int41BB:ON CD3:ON ] [ ]

,IL2 from master,IL2 from mutation,Difference IL2,Percentage IL2,Increase IL2
0,0.1918,0.4233,0.2315,120.70%,True

Query 11 : Inc(node:IL2) / [ ] [ int41BB:ON CD3:OFF ] [ ]

,IL2 from master,IL2 from mutation,Difference IL2,Percentage IL2,Increase IL2
0,0.1918,0.0,-0.1918,-100.00%,False

Query 12 : Inc(node:IL2) / [ ] [ CD3:ON int41BB:OFF ] [ ]

,IL2 from master,IL2 from mutation,Difference IL2,Percentage IL2,Increase IL2
0,0.1918,0.4186,0.2268,118.25%,True

CD4 endogenous CAR41BB IC
Query 1 : Inc(node:Apoptosis) / [ ] [ THEMIS:ON SHP1:ON ] [ ]

,Apoptosis from master,Apoptosis from mutation,Difference Apoptosis,Percentage Apoptosis,Increase Apoptosis
0,0.2654,0.2679,0.0025,0.94%,True

Query 2 : Inc(node:Apoptosis) / [ ] [ THEMIS:OFF SHP1:ON ] [ ]

,Apoptosis from master,Apoptosis from mutation,Difference Apoptosis,Percentage Apoptosis,Increase Apoptosis
0,0.2654,0.2675,0.0021,0.79%,True

Query 3 : Inc(node:Apoptosis) / [ ] [ THEMIS:ON SHP1:OFF ] [ ]

,Apoptosis from master,Apoptosis from mutation,Difference Apoptosis,Percentage Apoptosis,Increase Apoptosis
0,0.2654,0.2644,-0.001,-0.38%,False

In [7]:
tl.Visualiser(list_queries=CD8_list_random_ic, list_of_results=res_phenotypes).display_results_and_queries(title="CD8 endogenous Random IC")
tl.Visualiser(list_queries=CD8_list_abTCR_L41BB, list_of_results=res_abTCR_ic).display_results_and_queries(title="CD8 endogenous abTCR L41BB IC")
tl.Visualiser(list_queries=CD8_CAR41BB_i_c, list_of_results=res_CAR41BB_ic).display_results_and_queries(title="CD8 endogenous CAR41BB IC")

CD8 endogenous Random IC
Query 1 : Dec(node:Apoptosis) / [ ] [ int41BB:ON CD3:ON ] [ ]

,Th1 from master,Th1 from mutation,Difference Th1,Percentage Th1,Increase Th1
0,0.3709,0.4104,0.0395,10.65%,True

Query 2 : Dec(node:Apoptosis) / [ ] [ int41BB:ON CD3:OFF ] [ ]

,Th2 from master,Th2 from mutation,Difference Th2,Percentage Th2,Increase Th2
0,0.0021,0.0051,0.003,142.86%,True

CD8 endogenous abTCR L41BB IC
Query 1 : Dec(node:Apoptosis) / [ ] [ int41BB:ON CD3:ON ] [ ]

,Apoptosis from master,Apoptosis from mutation,Difference Apoptosis,Percentage Apoptosis,Decrease Apoptosis
0,0.2654,0.3097,0.0443,16.69%,False

Query 2 : Dec(node:Apoptosis) / [ ] [ int41BB:ON CD3:OFF ] [ ]

,Apoptosis from master,Apoptosis from mutation,Difference Apoptosis,Percentage Apoptosis,Decrease Apoptosis
0,0.2654,0.26,-0.0054,-2.03%,True

Query 3 : Dec(node:Apoptosis) / [ ] [ int41BB:OFF CD3:ON ] [ ]

,Apoptosis from master,Apoptosis from mutation,Difference Apoptosis,Percentage Apoptosis,Decrease Apoptosis
0,0.2654,0.3102,0.0448,16.88%,False

Query 4 : Inc(node:proliferation,IFNg,GZMB,GZMK,PRF1) / [ ] [ int41BB:ON CD3:ON ] [ ]

,proliferation from master,proliferation from mutation,Difference proliferation,Percentage proliferation,Increase proliferation,IFNg from master,IFNg from mutation,Difference IFNg,Percentage IFNg,Increase IFNg,GZMB from master,GZMB from mutation,Difference GZMB,Percentage GZMB,Increase GZMB,GZMK from master,GZMK from mutation,Difference GZMK,Percentage GZMK,Increase GZMK,PRF1 from master,PRF1 from mutation,Difference PRF1,Percentage PRF1,Increase PRF1
0,0.7059,0.6058,-0.1001,-14.18%,False,0.4687,0.4927,0.024,5.12%,True,0.4468,0.3644,-0.0824,-18.44%,False,0.6783,0.6921,0.0138,2.03%,True,0.6749,0.6918,0.0169,2.50%,True

Query 5 : Inc(node:proliferation,IFNg,GZMB,GZMK,PRF1) / [ ] [ int41BB:ON CD3:OFF ] [ ]

,proliferation from master,proliferation from mutation,Difference proliferation,Percentage proliferation,Increase proliferation,IFNg from master,IFNg from mutation,Difference IFNg,Percentage IFNg,Increase IFNg,GZMB from master,GZMB from mutation,Difference GZMB,Percentage GZMB,Increase GZMB,GZMK from master,GZMK from mutation,Difference GZMK,Percentage GZMK,Increase GZMK,PRF1 from master,PRF1 from mutation,Difference PRF1,Percentage PRF1,Increase PRF1
0,0.7059,0.7083,0.0024,0.34%,True,0.4687,0.4164,-0.0523,-11.16%,False,0.4468,0.4408,-0.006,-1.34%,False,0.6783,0.6587,-0.0196,-2.89%,False,0.6749,0.6558,-0.0191,-2.83%,False

Query 6 : Inc(node:proliferation,IFNg,GZMB,GZMK,PRF1) / [ ] [ int41BB:OFF CD3:ON ] [ ]

,proliferation from master,proliferation from mutation,Difference proliferation,Percentage proliferation,Increase proliferation,IFNg from master,IFNg from mutation,Difference IFNg,Percentage IFNg,Increase IFNg,GZMB from master,GZMB from mutation,Difference GZMB,Percentage GZMB,Increase GZMB,GZMK from master,GZMK from mutation,Difference GZMK,Percentage GZMK,Increase GZMK,PRF1 from master,PRF1 from mutation,Difference PRF1,Percentage PRF1,Increase PRF1
0,0.7059,0.6034,-0.1025,-14.52%,False,0.4687,0.4888,0.0201,4.29%,True,0.4468,0.3652,-0.0816,-18.26%,False,0.6783,0.6937,0.0154,2.27%,True,0.6749,0.6924,0.0175,2.59%,True

Query 7 : Inc(node:proliferation,IFNg,GZMB,GZMK,PRF1) / [ ] [ int41BB:ON CD3:ON ] [ comb ]

,proliferation from master,proliferation from mutation,Difference proliferation,Percentage proliferation,Increase proliferation,"P_cumul(proliferation,IFNg,GZMB,GZMK,PRF1) master","P_cumul(proliferation,IFNg,GZMB,GZMK,PRF1) mutation",Difference cumul,Percentage cumul,Increase cumul,IFNg from master,IFNg from mutation,Difference IFNg,Percentage IFNg,Increase IFNg,GZMB from master,GZMB from mutation,Difference GZMB,Percentage GZMB,Increase GZMB,GZMK from master,GZMK from mutation,Difference GZMK,Percentage GZMK,Increase GZMK,PRF1 from master,PRF1 from mutation,Difference PRF1,Percentage PRF1,Increase PRF1
0,0.7059,0.6058,-0.1001,-14.18%,False,0.3449,0.2734,-0.0715,-20.72%,False,0.4687,0.4927,0.024,5.12%,True,0.4468,0.3644,-0.0824,-18.44%,False,0.6783,0.6921,0.0138,2.03%,True,0.6749,0.6918,0.0169,2.50%,True

Query 8 : Inc(node:proliferation,IFNg,GZMB,GZMK,PRF1) / [ ] [ int41BB:ON CD3:OFF ] [ comb ]

,proliferation from master,proliferation from mutation,Difference proliferation,Percentage proliferation,Increase proliferation,"P_cumul(proliferation,IFNg,GZMB,GZMK,PRF1) master","P_cumul(proliferation,IFNg,GZMB,GZMK,PRF1) mutation",Difference cumul,Percentage cumul,Increase cumul,IFNg from master,IFNg from mutation,Difference IFNg,Percentage IFNg,Increase IFNg,GZMB from master,GZMB from mutation,Difference GZMB,Percentage GZMB,Increase GZMB,GZMK from master,GZMK from mutation,Difference GZMK,Percentage GZMK,Increase GZMK,PRF1 from master,PRF1 from mutation,Difference PRF1,Percentage PRF1,Increase PRF1
0,0.7059,0.7083,0.0024,0.34%,True,0.3449,0.3528,0.008,2.32%,True,0.4687,0.4164,-0.0523,-11.16%,False,0.4468,0.4408,-0.006,-1.34%,False,0.6783,0.6587,-0.0196,-2.89%,False,0.6749,0.6558,-0.0191,-2.83%,False

Query 9 : Inc(node:proliferation,IFNg,GZMB,GZMK,PRF1) / [ ] [ int41BB:OFF CD3:ON ] [ comb ]

,proliferation from master,proliferation from mutation,Difference proliferation,Percentage proliferation,Increase proliferation,"P_cumul(proliferation,IFNg,GZMB,GZMK,PRF1) master","P_cumul(proliferation,IFNg,GZMB,GZMK,PRF1) mutation",Difference cumul,Percentage cumul,Increase cumul,IFNg from master,IFNg from mutation,Difference IFNg,Percentage IFNg,Increase IFNg,GZMB from master,GZMB from mutation,Difference GZMB,Percentage GZMB,Increase GZMB,GZMK from master,GZMK from mutation,Difference GZMK,Percentage GZMK,Increase GZMK,PRF1 from master,PRF1 from mutation,Difference PRF1,Percentage PRF1,Increase PRF1
0,0.7059,0.6034,-0.1025,-14.52%,False,0.3449,0.2732,-0.0716,-20.77%,False,0.4687,0.4888,0.0201,4.29%,True,0.4468,0.3652,-0.0816,-18.26%,False,0.6783,0.6937,0.0154,2.27%,True,0.6749,0.6924,0.0175,2.59%,True

Query 10 : Inc(node:IL2) / [ ] [ int41BB:ON CD3:ON ] [ ]

,IL2 from master,IL2 from mutation,Difference IL2,Percentage IL2,Increase IL2
0,0.1918,0.4233,0.2315,120.70%,True

Query 11 : Inc(node:IL2) / [ ] [ int41BB:ON CD3:OFF ] [ ]

,IL2 from master,IL2 from mutation,Difference IL2,Percentage IL2,Increase IL2
0,0.1918,0.0,-0.1918,-100.00%,False

Query 12 : Inc(node:IL2) / [ ] [ CD3:ON int41BB:OFF ] [ ]

,IL2 from master,IL2 from mutation,Difference IL2,Percentage IL2,Increase IL2
0,0.1918,0.4186,0.2268,118.25%,True

CD8 endogenous CAR41BB IC
Query 1 : Inc(node:Apoptosis) / [ ] [ THEMIS:ON SHP1:ON ] [ ]

,Apoptosis from master,Apoptosis from mutation,Difference Apoptosis,Percentage Apoptosis,Increase Apoptosis
0,0.2654,0.2679,0.0025,0.94%,True

Query 2 : Inc(node:Apoptosis) / [ ] [ THEMIS:OFF SHP1:ON ] [ ]

,Apoptosis from master,Apoptosis from mutation,Difference Apoptosis,Percentage Apoptosis,Increase Apoptosis
0,0.2654,0.2675,0.0021,0.79%,True

Query 3 : Inc(node:Apoptosis) / [ ] [ THEMIS:ON SHP1:OFF ] [ ]

,Apoptosis from master,Apoptosis from mutation,Difference Apoptosis,Percentage Apoptosis,Increase Apoptosis
0,0.2654,0.2644,-0.001,-0.38%,False