In [1]:
import sys
import os

# this is needed only if maboss is not seen by Jupyter
path_dev = os.path.expanduser("/")
if path_dev not in sys.path:
    sys.path.insert(0, path_dev)

import maboss
from maboss import temporal_logic as tl

# Step 1 - Préparer les questions

Dans cette version de pyMaBoSS, toutes les simulations sont effectuées automatiquement.
Je vais utiliser les fichiers de configurations du BRAF pour faire la démonstration

Les questions doivent être un tableau de `string`, voilà les questions auxquelles on va répondre à travers cette démo :
- A quel(s) moment(s) la probabilité du node **AKT** est-elle supérieure à 0.4 ?
- A quel(s) moment(s) la probabilité du node **AKT** est-elle supérieure à 0.4 sachant que **BRAF** ET **Proliferation_b2** sont actifs aussi ?
- La première période de temps durant laquelle la probabilité de **MDM2** est supérieur ou égale à 0.7.
- Toutes les périodes où la probabilité de **p53** est supérieure à 0.5
## Voilà pour les assertions faciles à comprendre. Voici une vraie assertion qui implique une mutation, également gérée par la boucle.
- L'induction du chemin **PI3K-AKT** est associé à une diminution de la sensibilité de **MAPK** à l'inhibition. (Dans le programme **MAPK** est représenté par **Proliferation_b1** et **Proliferation_b2**)

## On enregistre les fichiers pour que ce soit plus facile

In [2]:
#Fichiers de config
file_bnd = "BRAF_Model.bnd"
file_cfg = "BRAF_Model.cfg"

## Puis on lance le programme

In [3]:
res = tl.MaBoSSEvaluator.querying(["Dec(node:Proliferation_b1,Proliferation_b2) / [ ] [ BRAF:OFF MEK_b1:OFF MEK_b2:OFF PI3K:OFF AKT:OFF ] [ 5% compare:BRAF:OFF,MEK_b1:OFF,MEK_b2:OFF,PI3K:OFF digits:6 ]"], file_cfg, file_bnd)

Evaluations done !

In [4]:
viz_test = tl.visualiser.Visualiser(list_queries=["Dec(node:Proliferation_b1,Proliferation_b2) / [ ] [ BRAF:OFF MEK_b1:OFF MEK_b2:OFF PI3K:OFF AKT:OFF ] [ 5% compare:BRAF:OFF,MEK_b1:OFF,MEK_b2:OFF,PI3K:OFF digits:6 ]"], list_of_results=res)
viz_test.display_results_and_queries("Test")

Test
Query 1 : Dec(node:Proliferation_b1,Proliferation_b2) / [ ] [ BRAF:OFF MEK_b1:OFF MEK_b2:OFF PI3K:OFF AKT:OFF ] [ 5% compare:BRAF:OFF,MEK_b1:OFF,MEK_b2:OFF,PI3K:OFF digits:6 ]

,Proliferation_b1 from master,Proliferation_b1 from mutation,Difference Proliferation_b1,Percentage Proliferation_b1,Decrease Proliferation_b1,Proliferation_b2 from master,Proliferation_b2 from mutation,Difference Proliferation_b2,Percentage Proliferation_b2,Decrease Proliferation_b2
0,0.0,0.0,0.0,0.00%,Stable,0.0,0.0,0.0,0.00%,Stable

In [9]:
assertion_test_simplified = "P(node:Proliferation_b1) >= 0.35 [ node:AKT & ( node:BRAF | node:MEK_b1 ) ]"
assertion_test_multiplied = "P(node:Proliferation_b1) >= 0.35 [ ( node:AKT & node:BRAF ) | ( node:AKT & node:MEK_b1 ) ]"
assertion_test_without_parentheses = "P(node:Proliferation_b1) >= 0.35 [ node:AKT & node:BRAF | node:MEK_b1 ]"
res_test = tl.MaBoSSEvaluator.querying([assertion_test_simplified, assertion_test_multiplied, assertion_test_without_parentheses], file_cfg, file_bnd)
viz_test = tl.visualiser.Visualiser(list_queries=[assertion_test_simplified, assertion_test_multiplied, assertion_test_without_parentheses], list_of_results=res_test)
viz_test.display_results_and_queries("Test")

Evaluations done !
Test
Query 1 : P(node:Proliferation_b1) >= 0.35 [ node:AKT & ( node:BRAF | node:MEK_b1 ) ]

    Time       AKT      BRAF    MEK_b1  Proliferation_b1
0    0.0  0.494795  0.435942  0.555932          0.481791
1    0.5  0.490578  0.359803  0.619218          0.446967
2    1.0  0.477933  0.304118  0.637600          0.431183
3    1.5  0.465940  0.265244  0.629784          0.428898
4    2.0  0.460210  0.238532  0.603951          0.427259
5    2.5  0.456126  0.216848  0.577793          0.427848
6    3.0  0.444623  0.199466  0.553907          0.422148
7    3.5  0.439329  0.187034  0.522782          0.408779
8    4.0  0.426826  0.181412  0.490173          0.396847
9    4.5  0.419527  0.175240  0.462863          0.382525
10   5.0  0.411785  0.166320  0.437679          0.366218

Query 2 : P(node:Proliferation_b1) >= 0.35 [ ( node:AKT & node:BRAF ) | ( node:AKT & node:MEK_b1 ) ]

    Time       AKT      BRAF    MEK_b1  Proliferation_b1
0    0.0  0.494795  0.435942  0.555932          0.481791
1    0.5  0.490578  0.359803  0.619218          0.446967
2    1.0  0.477933  0.304118  0.637600          0.431183
3    1.5  0.465940  0.265244  0.629784          0.428898
4    2.0  0.460210  0.238532  0.603951          0.427259
5    2.5  0.456126  0.216848  0.577793          0.427848
6    3.0  0.444623  0.199466  0.553907          0.422148
7    3.5  0.439329  0.187034  0.522782          0.408779
8    4.0  0.426826  0.181412  0.490173          0.396847
9    4.5  0.419527  0.175240  0.462863          0.382525
10   5.0  0.411785  0.166320  0.437679          0.366218

Query 3 : P(node:Proliferation_b1) >= 0.35 [ node:AKT & node:BRAF | node:MEK_b1 ]

    Time       AKT      BRAF    MEK_b1  Proliferation_b1
0    0.0  0.494795  0.435942  0.555932          0.481791
1    0.5  0.490578  0.359803  0.619218          0.446967
2    1.0  0.477933  0.304118  0.637600          0.431183
3    1.5  0.465940  0.265244  0.629784          0.428898
4    2.0  0.460210  0.238532  0.603951          0.427259
5    2.5  0.456126  0.216848  0.577793          0.427848
6    3.0  0.444623  0.199466  0.553907          0.422148
7    3.5  0.439329  0.187034  0.522782          0.408779
8    4.0  0.426826  0.181412  0.490173          0.396847
9    4.5  0.419527  0.175240  0.462863          0.382525
10   5.0  0.411785  0.166320  0.437679          0.366218

In [11]:
print(res_test[0].equals(res_test[1]))
print(res_test[0].equals(res_test[2]))
print(res_test[1].equals(res_test[2]))

True
True
True

In [12]:
import maboss
sim_test = maboss.load(file_bnd, file_cfg)
runned = sim_test.run()
runned.get_last_nodes_probtraj().columns.tolist()

['AKT',
 'ATM',
 'BRAF',
 'CRAF',
 'EGF',
 'EGFR',
 'ERBB2',
 'ERBB3',
 'ERK_b1',
 'ERK_b2',
 'FGF',
 'FGFR2',
 'FOXD3',
 'FRS2',
 'GAB1',
 'GRB2',
 'HGF',
 'MEK_b1',
 'MEK_b2',
 'MET',
 'PDPK1',
 'PI3K',
 'PTEN',
 'Proliferation_b1',
 'Proliferation_b2',
 'RAS',
 'RHEB',
 'SOS',
 'SOX10',
 'SPRY',
 'TSC2',
 'mTOR',
 'p21',
 'p53',
 'p70_b1',
 'p70_b2']