In [1]:
import sys
import os

# this is needed only if maboss is not seen by Jupyter
path_dev = os.path.expanduser("~/Documents/MaBoSS/pyMaBoSS")
if path_dev not in sys.path:
    sys.path.insert(0, path_dev)

import maboss
from maboss import temporal_logic as tl

# Step 1 - Préparer les questions

Dans cette version de pyMaBoSS, toutes les simulations sont effectuées automatiquement.
Je vais utiliser les fichiers de configurations du BRAF pour faire la démonstration

Les questions doivent être un tableau de `string`, voilà les questions auxquelles on va répondre à travers cette démo :
- A quel(s) moment(s) la probabilité du node **AKT** est-elle supérieure à 0.4 ?
- A quel(s) moment(s) la probabilité du node **AKT** est-elle supérieure à 0.4 sachant que **BRAF** ET **Proliferation_b2** sont actifs aussi ?
- La première période de temps durant laquelle la probabilité de **MDM2** est supérieur ou égale à 0.7.
- Toutes les périodes où la probabilité de **p53** est supérieure à 0.5
## Voilà pour les assertions faciles à comprendre. Voici une vraie assertion qui implique une mutation, également gérée par la boucle.
- L'induction du chemin **PI3K-AKT** est associé à une diminution de la sensibilité de **MAPK** à l'inhibition. (Dans le programme **MAPK** est représenté par **Proliferation_b1** et **Proliferation_b2**)

## On enregistre les fichiers pour que ce soit plus facile

In [2]:
#Fichiers de config
file_bnd = "BRAF_Model.bnd"
file_cfg = "BRAF_Model.cfg"

## Puis on lance le programme

In [3]:
res = tl.MaBoSSEvaluator.querying(["Dec(node:Proliferation_b1,Proliferation_b2) / [ ] [ BRAF:OFF MEK_b1:OFF MEK_b2:OFF PI3K:OFF AKT:OFF ] [ 5% compare:BRAF:OFF,MEK_b1:OFF,MEK_b2:OFF,PI3K:OFF digits:6 ]"], file_cfg, file_bnd)

query : Dec(node:Proliferation_b1,Proliferation_b2) / [ ] [ BRAF:OFF MEK_b1:OFF MEK_b2:OFF PI3K:OFF AKT:OFF ] [ 5% compare:BRAF:OFF,MEK_b1:OFF,MEK_b2:OFF,PI3K:OFF digits:6 ]
Combination : False
{'Proliferation_b1 from master': [0.0], 'Proliferation_b1 from mutation': [0.0], 'Difference Proliferation_b1': [0.0], 'Percentage Proliferation_b1': ['0.00%'], 'Decrease Proliferation_b1': 'Stable', 'Proliferation_b2 from master': [0.0], 'Proliferation_b2 from mutation': [0.0], 'Difference Proliferation_b2': [0.0], 'Percentage Proliferation_b2': ['0.00%'], 'Decrease Proliferation_b2': 'Stable'}
Evaluations done !

In [4]:
viz_test = tl.visualiser.Visualiser(list_queries=["Dec(node:Proliferation_b1,Proliferation_b2) / [ ] [ BRAF:OFF MEK_b1:OFF MEK_b2:OFF PI3K:OFF AKT:OFF ] [ 5% compare:BRAF:OFF,MEK_b1:OFF,MEK_b2:OFF,PI3K:OFF digits:6 ]"], list_of_results=res)
viz_test.display_results_and_queries("Test")

Test
Query 1 : Dec(node:Proliferation_b1,Proliferation_b2) / [ ] [ BRAF:OFF MEK_b1:OFF MEK_b2:OFF PI3K:OFF AKT:OFF ] [ 5% compare:BRAF:OFF,MEK_b1:OFF,MEK_b2:OFF,PI3K:OFF digits:6 ]

,Proliferation_b1 from master,Proliferation_b1 from mutation,Difference Proliferation_b1,Percentage Proliferation_b1,Decrease Proliferation_b1,Proliferation_b2 from master,Proliferation_b2 from mutation,Difference Proliferation_b2,Percentage Proliferation_b2,Decrease Proliferation_b2
0,0.0,0.0,0.0,0.00%,Stable,0.0,0.0,0.0,0.00%,Stable

In [5]:
assertion_test_simplified = "P(node:Proliferation_b1) >= 0.35 [ node:AKT & ( node:BRAF | node:MEK_b1 ) ]"
assertion_test_multiplied = "P(node:Proliferation_b1) >= 0.35 [ ( node:AKT & node:BRAF ) | ( node:AKT & node:MEK_b1 ) ]"
assertion_test_without_parentheses = "P(node:Proliferation_b1) >= 0.35 [ node:AKT & node:BRAF | node:MEK_b1 ]"
res_test = tl.MaBoSSEvaluator.querying([assertion_test_simplified, assertion_test_multiplied, assertion_test_without_parentheses], file_cfg, file_bnd)
viz_test = tl.visualiser.Visualiser(list_queries=[assertion_test_simplified, assertion_test_multiplied, assertion_test_without_parentheses], list_of_results=res_test)
viz_test.display_results_and_queries("Test")

query : P(node:Proliferation_b1) >= 0.35 [ node:AKT & ( node:BRAF | node:MEK_b1 ) ]
query : P(node:Proliferation_b1) >= 0.35 [ ( node:AKT & node:BRAF ) | ( node:AKT & node:MEK_b1 ) ]
query : P(node:Proliferation_b1) >= 0.35 [ node:AKT & node:BRAF | node:MEK_b1 ]
Evaluations done !
Test
Query 1 : P(node:Proliferation_b1) >= 0.35 [ node:AKT & ( node:BRAF | node:MEK_b1 ) ]

    Time       AKT      BRAF    MEK_b1  Proliferation_b1
0    0.0  0.499264  0.456342  0.574085          0.478913
1    0.5  0.499120  0.374441  0.641788          0.450303
2    1.0  0.498152  0.313104  0.652096          0.434192
3    1.5  0.492646  0.275081  0.642663          0.432844
4    2.0  0.480682  0.242654  0.615808          0.438985
5    2.5  0.479628  0.213856  0.578401          0.439150
6    3.0  0.471138  0.193254  0.546477          0.438049
7    3.5  0.458519  0.176039  0.508246          0.426295
8    4.0  0.446685  0.165142  0.476446          0.409054
9    4.5  0.437206  0.162688  0.448740          0.392792
10   5.0  0.422073  0.157614  0.428392          0.375087

Query 2 : P(node:Proliferation_b1) >= 0.35 [ ( node:AKT & node:BRAF ) | ( node:AKT & node:MEK_b1 ) ]

    Time       AKT      BRAF    MEK_b1  Proliferation_b1
0    0.0  0.499264  0.456342  0.574085          0.478913
1    0.5  0.499120  0.374441  0.641788          0.450303
2    1.0  0.498152  0.313104  0.652096          0.434192
3    1.5  0.492646  0.275081  0.642663          0.432844
4    2.0  0.480682  0.242654  0.615808          0.438985
5    2.5  0.479628  0.213856  0.578401          0.439150
6    3.0  0.471138  0.193254  0.546477          0.438049
7    3.5  0.458519  0.176039  0.508246          0.426295
8    4.0  0.446685  0.165142  0.476446          0.409054
9    4.5  0.437206  0.162688  0.448740          0.392792
10   5.0  0.422073  0.157614  0.428392          0.375087

Query 3 : P(node:Proliferation_b1) >= 0.35 [ node:AKT & node:BRAF | node:MEK_b1 ]

    Time       AKT      BRAF    MEK_b1  Proliferation_b1
0    0.0  0.499264  0.456342  0.574085          0.478913
1    0.5  0.499120  0.374441  0.641788          0.450303
2    1.0  0.498152  0.313104  0.652096          0.434192
3    1.5  0.492646  0.275081  0.642663          0.432844
4    2.0  0.480682  0.242654  0.615808          0.438985
5    2.5  0.479628  0.213856  0.578401          0.439150
6    3.0  0.471138  0.193254  0.546477          0.438049
7    3.5  0.458519  0.176039  0.508246          0.426295
8    4.0  0.446685  0.165142  0.476446          0.409054
9    4.5  0.437206  0.162688  0.448740          0.392792
10   5.0  0.422073  0.157614  0.428392          0.375087

In [6]:
print(res_test[0].equals(res_test[1]))
print(res_test[0].equals(res_test[2]))
print(res_test[1].equals(res_test[2]))

True
True
True

In [13]:
import maboss
sim_test = maboss.load(file_bnd, file_cfg)
runned = sim_test.run()
#runned.get_last_nodes_probtraj().columns.tolist()
display(runned.get_fptable())

,FP,Proba,State,p53,PTEN,PDPK1,AKT,PI3K,p70_b1,mTOR,p70_b2,ERK_b1,MEK_b1,ERK_b2,MEK_b2,Proliferation_b1,Proliferation_b2,p21,BRAF,CRAF,RAS,SOS,GRB2,SPRY,EGFR,MET,FRS2,ERBB3,GAB1,EGF,FOXD3,HGF,FGF,FGFR2,TSC2,RHEB,SOX10,ERBB2,ATM,MDM2
0,#1,0.0298,p53 -- PTEN -- p21 -- TSC2 -- ATM,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0
1,#2,0.0302,TSC2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0

In [8]:
assertion_5_a = "Inc(node:ERK_b1,MEK_b1) / [ ] [ CRAF:ON BRAF:OFF ] [ 5% digits:3 ]"
assertion_5_b = "Inc(node:ERK_b1,MEK_b1) / [ ] [ CRAF:ON ] [ 5% digits:3 ]"
res = tl.MaBoSSEvaluator.querying([assertion_5_a,assertion_5_b], file_cfg, file_bnd)
viz = tl.visualiser.Visualiser(list_queries=[assertion_5_a,assertion_5_b], list_of_results=res)
#viz.display_results_and_queries()

query : Inc(node:ERK_b1,MEK_b1) / [ ] [ CRAF:ON BRAF:OFF ] [ 5% digits:3 ]
Combination : False
{'ERK_b1 from master': [np.float64(0.461)], 'ERK_b1 from mutation': [np.float64(1.0)], 'Difference ERK_b1': [np.float64(0.5389999999999999)], 'Percentage ERK_b1': ['116.92%'], 'Increase ERK_b1': 'True', 'MEK_b1 from master': [np.float64(0.441)], 'MEK_b1 from mutation': [np.float64(1.0)], 'Difference MEK_b1': [np.float64(0.5589999999999999)], 'Percentage MEK_b1': ['126.76%'], 'Increase MEK_b1': 'True'}
query : Inc(node:ERK_b1,MEK_b1) / [ ] [ CRAF:ON ] [ 5% digits:3 ]
Combination : False
{'ERK_b1 from master': [np.float64(0.461)], 'ERK_b1 from mutation': [np.float64(1.0)], 'Difference ERK_b1': [np.float64(0.5389999999999999)], 'Percentage ERK_b1': ['116.92%'], 'Increase ERK_b1': 'True', 'MEK_b1 from master': [np.float64(0.441)], 'MEK_b1 from mutation': [np.float64(1.0)], 'Difference MEK_b1': [np.float64(0.5589999999999999)], 'Percentage MEK_b1': ['126.76%'], 'Increase MEK_b1': 'True'}
Evaluations done !

In [15]:
model_braf_off = sim_test.copy()
model_master = sim_test.run()
model_braf_off.mutate("CRAF","ON")
model_braf_off.mutate("BRAF","OFF")
sim_braf_off = model_braf_off.run()
print(model_master.get_last_nodes_probtraj().columns.tolist())
print(sim_braf_off.get_last_nodes_probtraj().columns.tolist())
#print("master")
#display(model_master.get_last_nodes_probtraj())
#print("braf_off craf_on")
#display(sim_braf_off.get_last_nodes_probtraj())

#display(sim_braf_off.get_last_states_probtraj())
#display(sim_braf_off.get_fptable())

['AKT', 'ATM', 'BRAF', 'CRAF', 'EGF', 'EGFR', 'ERBB2', 'ERBB3', 'ERK_b1', 'ERK_b2', 'FGF', 'FGFR2', 'FOXD3', 'FRS2', 'GAB1', 'GRB2', 'HGF', 'MEK_b1', 'MEK_b2', 'MET', 'PDPK1', 'PI3K', 'PTEN', 'Proliferation_b1', 'Proliferation_b2', 'RAS', 'RHEB', 'SOS', 'SOX10', 'SPRY', 'TSC2', 'mTOR', 'p21', 'p53', 'p70_b1', 'p70_b2']
['AKT', 'ATM', 'CRAF', 'EGF', 'ERK_b1', 'FGF', 'FGFR2', 'FRS2', 'GAB1', 'HGF', 'MEK_b1', 'MET', 'PDPK1', 'PI3K', 'PTEN', 'Proliferation_b1', 'Proliferation_b2', 'RHEB', 'SOX10', 'SPRY', 'TSC2', 'mTOR', 'p21', 'p53', 'p70_b1', 'p70_b2']

In [10]:
print(sim_braf_off.get_last_nodes_probtraj()[["AKT","PI3K"]].iloc[0].sum())

0.4908

In [11]:
MEK_inhibition = 'MEK_b1:OFF MEK_b2:OFF'
assertions_list_no_i_s= []
assertion_2_a = f"Dec(node:ERK_b1,ERK_b2) / [ ] [ {MEK_inhibition} ] [ 5% digits:3 ]"
assertion_2_b = f"Inc(node:PI3K,AKT) / [ ] [ {MEK_inhibition} ] [ 5% digits:3 comb ]"
assertion_2_c = f"Inc(node:EGFR,ERBB3) / [ ] [ {MEK_inhibition} ] [ 5% digits:3 comb transient ]"
assertion_2_d = f"Inc(node:EGFR,ERBB3,PI3K,AKT) / [ ] [ {MEK_inhibition} ] [ 5% digits:3 ]"
assertion_2_e = f"Inc(state:AKT,PI3K) / [ ] [ {MEK_inhibition} ] [ 5% digits:3 comb ]"
#assertions_list_no_i_s.append(assertion_2_a)
#assertions_list_no_i_s.append(assertion_2_b)
#assertions_list_no_i_s.append(assertion_2_c)
#assertions_list_no_i_s.append(assertion_2_d)
assertions_list_no_i_s.append(assertion_2_e)
#assertions_list_no_i_s.append("")
res = tl.MaBoSSEvaluator.querying(assertions_list_no_i_s, file_cfg, file_bnd)
print("---------")
viz = tl.visualiser.Visualiser(list_queries=assertions_list_no_i_s, list_of_results=res)
viz.display_results_and_queries()

query : Inc(state:AKT,PI3K) / [ ] [ MEK_b1:OFF MEK_b2:OFF ] [ 5% digits:3 comb ]
Combination : True
{'P_cumul(AKT,PI3K) master': np.float64(0.329), 'P_cumul(AKT,PI3K) mutation': np.float64(0.476), 'Increase cumul': ['True']}
Evaluations done !
---------
Query 1 : Inc(state:AKT,PI3K) / [ ] [ MEK_b1:OFF MEK_b2:OFF ] [ 5% digits:3 comb ]

   P_cumul(AKT,PI3K) master  P_cumul(AKT,PI3K) mutation Increase cumul
0                     0.329                       0.476           True